import qrcode from './assets/vendor/qrcode.mjs';
import { getLocale, t, translateDocument } from './assets/js/i18n/index.js';
import { initLayout } from './assets/js/layouts.js';
import { showToast } from './assets/js/ui/components.js';
import { ACTION_PERMISSIONS, CONTROL_NAV, CONTROL_VIEWS, CONTROL_COLUMNS, CONTROL_STATUSES, STAFF_ROLES, VIEW_PERMISSIONS, actionFor as controlActionFor, createActionFor as createControlActionFor } from './admin-control-center.js';

const NAV = [
  ['adminOperations',[['dashboard','layout-dashboard','adminDashboard'],['users','users','adminUsers'],['stations','map-pinned','adminStations'],['bikes','bike','adminBikes'],['rides','route','adminRides']]],
  ['adminCommercial',[['plans','badge-percent','adminPlans'],['subscriptions','calendar-check','adminSubscriptions'],['payments','credit-card','adminPayments']]],
  ['adminService',[['incidents','triangle-alert','adminIncidents'],['maintenance','wrench','adminMaintenance'],['support','life-buoy','adminSupport'],['notifications','bell','adminNotifications']]],
  ['adminGovernance',[['settings','settings','adminSettings'],['audit','scroll-text','adminAudit']]],
  ...CONTROL_NAV
];

const state={view:new URLSearchParams(location.search).get('view')||'dashboard',page:1,search:'',status:'',role:'',data:null,user:null};
const host=document.querySelector('[data-admin-view]');const dialog=document.querySelector('[data-admin-dialog]');const confirmDialog=document.querySelector('[data-admin-confirm]');

function element(tag,className,content){const node=document.createElement(tag);if(className)node.className=className;if(content!==undefined)node.textContent=String(content);return node;}
function icon(name){const item=element('i');item.dataset.lucide=name;item.setAttribute('aria-hidden','true');return item;}
function refreshIcons(){window.lucide?.createIcons?.();}
function localizedDate(value,withTime=false){if(!value)return '—';const date=new Date(String(value).endsWith('Z')?value:`${String(value).replace(' ','T')}Z`);return Number.isNaN(date.valueOf())?'—':new Intl.DateTimeFormat(getLocale(),withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'medium'}).format(date);}
function money(minor,currency='MAD'){return new Intl.NumberFormat(getLocale(),{style:'currency',currency}).format(Number(minor||0)/100);}
function duration(value){const seconds=Number(value||0);return `${Math.floor(seconds/60)} min`;}
function statusTone(value){return ['failed','disabled','suspended','critical','closed','cancelled','refunded'].includes(String(value))?'is-danger':['pending','maintenance','in_progress','waiting_user','degraded'].includes(String(value))?'is-warning':'';}

async function api(path,options={}){let response;try{response=await fetch(path,{...options,credentials:'same-origin',headers:{'content-type':'application/json','x-pikala-request':'web',...(options.headers||{})}});}catch{throw new Error(t('adminLoadError'));}const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||t('adminLoadError'));error.status=response.status;error.code=data.code;throw error;}return data;}

async function requireAdmin(){try{const data=await api('/api/admin/session');if(!data.user?.permissions?.includes('staff.access')&&!data.user?.permissions?.includes('*')){location.assign('/dashboard.html?access=denied');return false;}state.user=data.user;document.querySelector('[data-admin-name]').textContent=`${data.user.first_name} ${data.user.last_name}`;document.querySelector('[data-admin-email]').textContent=data.user.email;document.querySelector('[data-admin-initials]').textContent=`${data.user.first_name?.[0]||''}${data.user.last_name?.[0]||''}`.toUpperCase();return true;}catch(error){location.assign(`/connexion.html?next=${encodeURIComponent('/admin.html')}`);return false;}}

function can(permission){return state.user?.permissions?.includes('*')||state.user?.permissions?.includes(permission);}
function canView(view){return can(VIEW_PERMISSIONS[view]||'staff.access')||(view==='missions'&&can('missions.read_assigned'));}
function mountNav(){const nav=document.querySelector('[data-admin-nav]');nav.replaceChildren();NAV.forEach(([group,items])=>{const visible=items.filter(([view])=>canView(view));if(!visible.length)return;nav.append(element('p','admin-nav-group',t(group)));visible.forEach(([view,iconName,key])=>{const button=element('button',view===state.view?'is-active':'');button.type='button';button.dataset.view=view;button.append(icon(iconName),document.createTextNode(t(key)));button.addEventListener('click',()=>navigate(view));nav.append(button);});});refreshIcons();}
function viewLabel(view){for(const [,items]of NAV){const item=items.find(([name])=>name===view);if(item)return t(item[2]);}return t('adminDashboard');}
function navigate(view,{replace=false}={}){state.view=view;state.page=1;state.search='';state.status='';state.role='';const url=new URL(location.href);url.searchParams.set('view',view);history[replace?'replaceState':'pushState']({},'',url);mountNav();closeSidebar();loadView();}
function closeSidebar(){document.querySelector('[data-admin-sidebar]').classList.remove('is-open');document.querySelector('[data-admin-backdrop]').classList.remove('is-open');}

function loading(){host.setAttribute('aria-busy','true');const wrapper=element('div','admin-loading');wrapper.append(element('span','pk-loader'),element('p','',t('adminLoading')));host.replaceChildren(wrapper);}
function errorState(error){host.setAttribute('aria-busy','false');const wrapper=element('div','admin-state');wrapper.append(icon('circle-alert'),element('h2','',t('adminLoadError')),element('p','',error.message));const retry=element('button','button primary',t('adminRetry'));retry.addEventListener('click',loadView);wrapper.append(retry);host.replaceChildren(wrapper);refreshIcons();}
function emptyRow(columns){const row=element('tr');const cell=element('td','admin-empty',t('adminEmpty'));cell.colSpan=columns;row.append(cell);return row;}
function badge(value){return element('span',`admin-badge ${statusTone(value)}`,String(value||'—').replaceAll('_',' '));}

function toolbar({statuses=[],roles=[],add=false}={}){const bar=element('div','admin-toolbar');const search=element('input');search.type='search';search.placeholder=t('adminSearch');search.value=state.search;let timer;search.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=search.value.trim();state.page=1;loadView();},300);});bar.append(search);
  if(statuses.length){const select=element('select');select.append(new Option(t('adminAllStatuses'),''),...statuses.map((item)=>new Option(item.replaceAll('_',' '),item)));select.value=state.status;select.addEventListener('change',()=>{state.status=select.value;state.page=1;loadView();});bar.append(select);}else bar.append(element('span'));
  if(roles.length){const select=element('select');select.append(new Option(t('adminAllRoles'),''),...roles.map((item)=>new Option(item,item)));select.value=state.role;select.addEventListener('change',()=>{state.role=select.value;state.page=1;loadView();});bar.append(select);}else bar.append(element('span'));
  const action=element('button','button primary',add?t('adminAdd'):t('adminRefresh'));action.type='button';action.prepend(icon(add?'plus':'refresh-cw'));action.addEventListener('click',()=>add?createForView():loadView());bar.append(action);return bar;}

const COLUMNS={
  users:[['id','ID'],['name','adminName'],['email','adminEmail'],['role','adminRole'],['status','adminStatus'],['plan_name','adminPlan'],['created_at','adminCreated']],
  stations:[['public_code','adminCode'],['name','adminName'],['address','adminAddress'],['bikes_available','adminBikes'],['docks_available','adminAvailable'],['dock_count','adminDocks'],['is_active','adminStatus']],
  bikes:[['public_code','adminCode'],['model','adminModel'],['serial_number','adminSerial'],['station_name','adminStation'],['status','adminStatus'],['last_ride_at','adminLastLogin'],['open_maintenance','adminMaintenance']],
  rides:[['id','ID'],['email','adminUser'],['bike_code','adminBike'],['start_station','adminDeparture'],['end_station','adminArrival'],['started_at','adminStart'],['duration_seconds','adminDuration'],['status','adminStatus'],['charged_amount_minor','adminPrice']],
  plans:[['slug','adminCode'],['name','adminName'],['amountMinor','adminPrice'],['durationDays','adminDuration'],['status','adminStatus'],['displayOrder','#']],
  subscriptions:[['id','ID'],['email','adminUser'],['plan_name','adminPlan'],['status','adminStatus'],['current_period_start','adminStart'],['current_period_end','adminEnd']],
  payments:[['public_reference','adminReference'],['email','adminUser'],['plan_name','adminPlan'],['amount_minor','adminAmount'],['provider','adminProvider'],['status','adminStatus'],['created_at','adminDate']],
  incidents:[['public_code','adminReference'],['bike_code','adminBike'],['incident_type','adminCategory'],['severity','adminSeverity'],['status','adminStatus'],['assignee_email','adminAssigned'],['created_at','adminDate']],
  maintenance:[['id','ID'],['bike_code','adminBike'],['reason','adminReason'],['workflow_stage','adminStatus'],['assignee_email','adminAssigned'],['opened_at','adminStart'],['resolved_at','adminEnd']],
  support:[['public_code','adminReference'],['email','adminUser'],['subject','adminSubject'],['topic','adminCategory'],['priority','adminPriority'],['status','adminStatus'],['assignee_email','adminAssigned'],['created_at','adminDate']],
  notifications:[['id','ID'],['email','adminUser'],['title','adminSubject'],['type','adminCategory'],['channel','Canal'],['status','adminStatus'],['created_at','adminDate']],
  audit:[['created_at','adminDate'],['admin_email','Admin'],['action','adminAction'],['target_type','adminResource'],['target_id','ID'],['metadata_json','adminMetadata']]
};
Object.assign(COLUMNS,CONTROL_COLUMNS);

function cellValue(view,key,item){if((key==='name'&&view==='users')||(key==='first_name'&&view==='employees'))return `${item.first_name||''} ${item.last_name||''}`.trim();if(key==='is_active')return item[key]?t('adminActive'):t('adminDisabled');if(['created_at','last_login_at','last_ride_at','started_at','current_period_start','current_period_end','opened_at','resolved_at','updated_at','due_at','completed_at','last_run_at','last_seen_at','detected_at','acknowledged_at','ends_at','starts_at'].includes(key))return localizedDate(item[key],key.includes('at'));if(key==='duration_seconds')return duration(item[key]);if(key==='charged_amount_minor'||key==='amount_minor')return money(item[key],item.currency);if(key==='amountMinor')return money(item[key],item.currency);if(key==='durationDays')return `${item[key]} j`;return item[key]??'—';}
function canAct(view){if(view==='employees')return can('employees.manage');if(['subscriptions','payments','audit','overrides','inspections'].includes(view))return false;if(CONTROL_VIEWS.has(view)){const spec=controlActionFor(view,{});return Boolean(spec&&can(ACTION_PERMISSIONS[spec.action]));}const manage={users:'users.manage',stations:'stations.manage',bikes:'bikes.manage',rides:'rides.force_end',plans:'plans.manage',incidents:'incidents.manage',maintenance:'maintenance.manage',support:'support.manage',notifications:'notifications.send'}[view];return Boolean(manage&&can(manage));}

function table(view,items){const wrap=element('div','admin-table-wrap');const tableEl=element('table','admin-table');const head=element('thead');const headRow=element('tr');COLUMNS[view].forEach(([,label])=>headRow.append(element('th','',label==='ID'||label==='#'||label==='Admin'||label==='Canal'?label:t(label))));if(canAct(view))headRow.append(element('th','',t('adminActions')));head.append(headRow);tableEl.append(head);const body=element('tbody');
  if(!items.length)body.append(emptyRow(COLUMNS[view].length+(canAct(view)?1:0)));items.forEach((item)=>{const row=element('tr',item.is_long?'is-alert':'');COLUMNS[view].forEach(([key])=>{const cell=element('td');const value=cellValue(view,key,item);if(key==='status'||key==='workflow_stage'||key==='is_active'||key==='severity'||key==='priority')cell.append(badge(value));else cell.textContent=value;row.append(cell);});if(canAct(view)){const actions=element('td','admin-table-actions');const viewButton=element('button','icon-button');viewButton.type='button';viewButton.title=t(view==='incidents'||view==='maintenance'||view==='support'?'adminEdit':'adminView');viewButton.append(icon(view==='incidents'||view==='maintenance'||view==='support'?'pencil':'eye'));viewButton.addEventListener('click',()=>actOn(view,item));actions.append(viewButton);if(view==='stations'){const disable=element('button','icon-button');disable.type='button';disable.title=t('adminDisable');disable.append(icon('power'));disable.addEventListener('click',()=>disableStation(item));actions.append(disable);}row.append(actions);}body.append(row);});tableEl.append(body);wrap.append(tableEl);return wrap;}

function pagination(data){if(!data.pagination)return element('div');const wrapper=element('div','admin-pagination');wrapper.append(element('span','',`${t('adminResults',{count:data.pagination.total})} · ${t('adminPage',{page:data.pagination.page,pages:data.pagination.pages})}`));const controls=element('div');const previous=element('button','button',t('adminPrevious'));previous.disabled=data.pagination.page<=1;previous.addEventListener('click',()=>{state.page-=1;loadView();});const next=element('button','button',t('adminNext'));next.disabled=data.pagination.page>=data.pagination.pages;next.addEventListener('click',()=>{state.page+=1;loadView();});controls.append(previous,next);wrapper.append(controls);return wrapper;}

function listOptions(view){if(view==='employees')return{statuses:CONTROL_STATUSES.employees,roles:STAFF_ROLES,add:can('employees.manage')};if(CONTROL_VIEWS.has(view)){const spec=createControlActionFor(view);return{statuses:CONTROL_STATUSES[view]||[],roles:[],add:Boolean(spec&&can(ACTION_PERMISSIONS[spec.action]))};}const statuses={users:['active','suspended','disabled'],stations:['active','inactive'],bikes:['available','in_use','maintenance','disabled','lost','retired'],rides:['active','completed','cancelled','disputed'],plans:['draft','active','archived','legacy'],subscriptions:['pending','active','cancelled','expired'],payments:['pending','processing','paid','failed','cancelled','refunded'],incidents:['open','triaged','in_progress','resolved','closed'],maintenance:['reported','to_inspect','maintenance','repaired','available'],support:['open','in_progress','waiting_user','resolved','closed'],notifications:['pending','sent','failed','read']}[view]||[];return{statuses,roles:view==='users'?['user','support','operator','admin']:[],add:['stations','bikes','plans','notifications'].includes(view)};}

async function renderList(view){const endpoint=view==='employees'?'/api/admin/staff':view==='audit'?'/api/admin/audit-logs':CONTROL_VIEWS.has(view)?`/api/admin/control-center/${view}`:`/api/admin/${view}`;const params=new URLSearchParams({page:state.page,limit:'25'});if(state.search)params.set('search',state.search);if(state.status)params.set('status',state.status);if(state.role)params.set('role',state.role);const data=await api(`${endpoint}?${params}`);const items=data.items||data.plans||[];if(data.plans&&!data.pagination)data.pagination={page:1,pages:1,total:items.length,limit:items.length};state.data=data;host.replaceChildren(toolbar(listOptions(view)));if(view==='payments'){const notice=element('div','admin-panel');notice.style.marginBottom='12px';notice.append(icon('shield-check'),document.createTextNode(` ${t('adminNoPaymentMutation')}`));host.append(notice);}host.append(table(view,items),pagination(data));host.setAttribute('aria-busy','false');refreshIcons();}

async function renderDashboard(){const data=await api('/api/admin/control-center');const service=element('section',`admin-service-banner is-${data.service.computedMode}`);service.append(icon(data.service.computedMode==='operational'?'circle-check':'triangle-alert'));const serviceCopy=element('div');serviceCopy.append(element('span','',t('adminServiceState')),element('strong','',data.service.computedMode),element('p','',data.service.message||t('adminServiceOperational')));service.append(serviceCopy);
  const grid=element('div','admin-metrics');const metrics=[['activeUsers','users','adminMetricsActiveUsers'],['bikes.total','bike','adminMetricsTotalBikes'],['bikes.available','circle-check','adminMetricsAvailableBikes'],['bikes.inUse','scan-line','adminMetricsInUseBikes'],['bikes.maintenance','wrench','adminMetricsMaintenanceBikes'],['bikes.unavailable','ban','adminMetricsUnavailableBikes'],['stations.normal','map-pin-check','adminMetricsNormalStations'],['stations.weak','battery-low','adminMetricsWeakStations'],['stations.full','circle-parking','adminMetricsFullStations'],['activeRides','route','adminMetricsActiveRides'],['openIncidents','triangle-alert','adminMetricsIncidents'],['overdueMaintenance','clock-alert','adminMetricsOverdueMaintenance'],['criticalTickets','life-buoy','adminMetricsCriticalTickets'],['overdueMissions','clipboard-x','adminMetricsOverdueMissions'],['offlineDevices','wifi-off','adminMetricsOfflineDevices']];metrics.forEach(([path,iconName,key])=>{const value=path.split('.').reduce((result,part)=>result?.[part],data.metrics)??0;const card=element('article','admin-metric');card.append(icon(iconName),element('strong','',value),element('span','',t(key)));grid.append(card);});
  const attention=element('section','admin-attention');const head=element('div','admin-section-title');head.append(element('div','',t('adminAttention')),badge(data.attention.length));attention.append(head);const list=element('div','admin-attention-list');if(!data.attention.length)list.append(element('p','admin-empty',t('adminNoAttention')));data.attention.forEach((item)=>{const row=element('article',`admin-attention-row is-${item.severity}`);row.append(icon(item.severity==='critical'?'circle-alert':'triangle-alert'));const copy=element('div');copy.append(element('strong','',item.title),element('p','',item.message));row.append(copy,badge(item.severity));list.append(row);});attention.append(list);
  const health=element('section','admin-panel admin-health-panel');health.append(element('h2','',t('adminSystem')));const statuses=element('div','admin-status-list');Object.entries(data.configuration).forEach(([key,value])=>{const row=element('div','admin-status-row');row.append(element('span','',key),badge(value));statuses.append(row);});health.append(statuses);host.replaceChildren(service,controlCommandBar(),grid,attention,health);host.setAttribute('aria-busy','false');state.data=data;refreshIcons();}

function fieldNode(field,initial={}){const label=element('label',field.wide?'is-wide':'');label.append(document.createTextNode(t(field.label)));let input;if(field.type==='select'){input=element('select');field.options.forEach(([value,key])=>input.append(new Option(key.startsWith('admin')?t(key):key,value)));}else if(field.type==='textarea'){input=element('textarea');}else{input=element('input');input.type=field.type||'text';}input.name=field.name;if(field.required)input.required=true;if(field.minLength!==undefined)input.minLength=field.minLength;if(field.maxLength!==undefined)input.maxLength=field.maxLength;if(field.min!==undefined)input.min=field.min;if(field.max!==undefined)input.max=field.max;if(field.step)input.step=field.step;const value=initial[field.name];if(field.type==='checkbox'){input.checked=Boolean(value);}else if(value!==undefined&&value!==null)input.value=typeof value==='object'?JSON.stringify(value,null,2):value;label.append(input);return label;}
function openForm(title,fields,initial,onSubmit){document.querySelector('[data-dialog-title]').textContent=title;const content=document.querySelector('[data-dialog-content]');const form=element('form','admin-form');fields.forEach((field)=>form.append(fieldNode(field,initial)));const actions=element('div','admin-form-actions');const cancel=element('button','button secondary',t('adminCancel'));cancel.type='button';cancel.addEventListener('click',()=>dialog.close());const save=element('button','button primary',t('adminSave'));save.type='submit';actions.append(cancel,save);form.append(actions);form.addEventListener('submit',async(event)=>{event.preventDefault();save.disabled=true;const data=Object.fromEntries(new FormData(form));fields.filter((field)=>field.type==='checkbox').forEach((field)=>{data[field.name]=form.elements[field.name].checked;});fields.filter((field)=>field.type==='number').forEach((field)=>{data[field.name]=form.elements[field.name].value===''?null:Number(form.elements[field.name].value);});try{await onSubmit(data);dialog.close();showToast(t('adminSave'),{tone:'success'});await loadView();}catch(error){showToast(error.message,{tone:'error'});save.disabled=false;}});content.replaceChildren(form);dialog.showModal();refreshIcons();}
function confirmAction(message){document.querySelector('[data-confirm-message]').textContent=message;confirmDialog.showModal();return new Promise((resolve)=>{confirmDialog.addEventListener('close',()=>resolve(confirmDialog.returnValue==='confirm'),{once:true});});}

const stationFields=[{name:'name',label:'adminName',required:true},{name:'publicCode',label:'adminCode',required:true},{name:'slug',label:'Slug',required:true},{name:'city',label:'adminCity',required:true},{name:'address',label:'adminAddress',wide:true},{name:'latitude',label:'Latitude',type:'number',step:'any',required:true},{name:'longitude',label:'Longitude',type:'number',step:'any',required:true},{name:'capacity',label:'adminCapacity',type:'number',min:0,max:100},{name:'dockCount',label:'adminDocks',type:'number',min:0,max:100},{name:'isActive',label:'adminActive',type:'checkbox'},{name:'openingHours',label:'Horaires JSON',type:'textarea',wide:true}];
const bikeFields=[{name:'publicCode',label:'adminCode',required:true},{name:'code',label:'Code interne',required:true},{name:'model',label:'adminModel'},{name:'serialNumber',label:'adminSerial'},{name:'stationId',label:'Station ID',type:'number',min:1},{name:'batteryLevel',label:'Batterie',type:'number',min:0,max:100},{name:'status',label:'adminStatus',type:'select',options:['available','reserved','in_use','maintenance','disabled','lost','retired'].map((item)=>[item,item])}];
const planFields=[{name:'slug',label:'adminCode',required:true},{name:'name',label:'adminName',required:true},{name:'description',label:'Description',type:'textarea',wide:true},{name:'amountMinor',label:'Montant (centimes)',type:'number',min:0},{name:'currency',label:'Devise'},{name:'durationDays',label:'Jours',type:'number',min:1},{name:'billingPeriod',label:'Période',type:'select',options:['day','week','month','year','one_time'].map((item)=>[item,item])},{name:'status',label:'adminStatus',type:'select',options:['draft','active','archived','legacy'].map((item)=>[item,item])},{name:'displayOrder',label:'Ordre',type:'number'},{name:'featured',label:'Recommandé',type:'checkbox'},{name:'benefitsText',label:'Avantages (une ligne chacun)',type:'textarea',wide:true}];

function normalizeStation(data){try{data.openingHours=JSON.parse(data.openingHours||'{}');}catch{throw new Error('Horaires JSON invalides.');}return data;}
const staffFields=[{name:'email',label:'adminEmail',type:'email',required:true},{name:'employeeCode',label:'adminCode',required:true},{name:'role',label:'adminRole',type:'select',options:STAFF_ROLES.map((role)=>[role,role])},{name:'hireDate',label:'adminHireDate',type:'date',required:true},{name:'zoneIdsText',label:'adminZones',required:true},{name:'reason',label:'adminReason',type:'textarea',wide:true,required:true,minLength:10,maxLength:500},{name:'confirmation',label:'PIKALA STAFF.CREATE',required:true}];
function staffPayload(values,action){return{...values,zoneIds:String(values.zoneIdsText||'').split(',').map((value)=>Number(value.trim())).filter(Number.isInteger),idempotencyKey:crypto.randomUUID(),confirmation:`PIKALA ${action}`};}
function createForView(){if(state.view==='employees')return openForm(t('adminEmployees'),staffFields,{hireDate:new Date().toISOString().slice(0,10),role:'field_agent',zoneIdsText:'1'},(data)=>api('/api/admin/staff',{method:'POST',body:JSON.stringify(staffPayload(data,'STAFF.CREATE'))}));const controlSpec=createControlActionFor(state.view);if(controlSpec)return openControlAction(controlSpec);if(state.view==='stations')openForm(t('adminAdd'),stationFields,{city:'Rabat',latitude:34.0209,longitude:-6.8416,capacity:10,dockCount:10,isActive:true,openingHours:{}},(data)=>api('/api/admin/stations',{method:'POST',body:JSON.stringify(normalizeStation(data))}));else if(state.view==='bikes')openForm(t('adminAdd'),bikeFields,{status:'available',batteryLevel:100},(data)=>api('/api/admin/bikes',{method:'POST',body:JSON.stringify(data)}));else if(state.view==='plans')openForm(t('adminAdd'),planFields,{currency:'MAD',durationDays:30,billingPeriod:'month',status:'draft',displayOrder:0},(data)=>api('/api/admin/plans',{method:'POST',body:JSON.stringify({...data,benefits:data.benefitsText.split('\n').map((x)=>x.trim()).filter(Boolean),translations:{}})}));else if(state.view==='notifications')notificationForm();}

async function actOn(view,item){if(view==='employees')return staffDialog(item.id);const controlSpec=controlActionFor(view,item);if(controlSpec)return openControlAction(controlSpec);if(view==='users')return userDialog(item.id);if(view==='stations')return stationDialog(item.id);if(view==='bikes')return bikeDialog(item.id);if(view==='rides')return rideDialog(item.id);if(view==='plans')return planDialog(item);if(view==='incidents')return workflowDialog('incident',item);if(view==='maintenance')return workflowDialog('maintenance',item);if(view==='support')return workflowDialog('support',item);}

async function staffDialog(id){const data=await api(`/api/admin/staff/${id}`);const member=data.member;const content=element('div');const details=element('div','admin-detail-grid');[['adminName',`${member.first_name} ${member.last_name}`],['adminEmail',member.email],['adminPhone',member.phone||'—'],['adminCode',member.employee_code],['adminRole',member.role],['adminStatus',member.status],['adminHireDate',localizedDate(member.hire_date)],['adminLastActivity',localizedDate(member.last_activity_at,true)],['adminZones',data.zones.map((zone)=>zone.name).join(', ')||'—']].forEach(([key,value])=>{const item=element('div');item.append(element('span','',t(key)),element('strong','',value));details.append(item);});content.append(details);const history=element('div','admin-section-title');history.append(element('h3','',t('adminActivity')),element('span','',data.activity.length));content.append(history);data.activity.slice(0,12).forEach((row)=>content.append(element('p','',`${localizedDate(row.created_at,true)} · ${row.action} · ${row.actor_email||'system'}`)));if(can('employees.manage')){const edit=element('button','button primary',t('adminEdit'));edit.addEventListener('click',()=>{dialog.close();const fields=[{name:'role',label:'adminRole',type:'select',options:STAFF_ROLES.map((role)=>[role,role])},{name:'status',label:'adminStatus',type:'select',options:['active','suspended','inactive'].map((status)=>[status,status])},{name:'hireDate',label:'adminHireDate',type:'date'},{name:'zoneIdsText',label:'adminZones'},{name:'reason',label:'adminReason',type:'textarea',wide:true,required:true,minLength:10,maxLength:500},{name:'confirmation',label:'PIKALA STAFF.UPDATE',required:true}];openForm(t('adminEmployees'),fields,{role:member.role,status:member.status,hireDate:member.hire_date||'',zoneIdsText:data.zones.map((zone)=>zone.id).join(',')},(values)=>api(`/api/admin/staff/${id}`,{method:'PATCH',body:JSON.stringify(staffPayload(values,'STAFF.UPDATE'))}));});content.append(edit);}showCustomDialog(t('adminEmployees'),content);}
async function userDialog(id){
  const data=await api(`/api/admin/users/${id}`);const user=data.user;const content=element('div');const details=element('div','admin-detail-grid');
  [['adminName',`${user.first_name} ${user.last_name}`],['adminEmail',user.email],['adminPhone',user.phone||'—'],['adminRole',user.role],['adminStatus',user.status],['adminLocale',user.locale],['adminCreated',localizedDate(user.created_at,true)],['adminLastLogin',localizedDate(user.last_login_at,true)],['adminPlan',user.plan_name||'—'],['adminEnd',localizedDate(user.current_period_end)]].forEach(([key,value])=>{const item=element('div');item.append(element('span','',t(key)),element('strong','',value));details.append(item);});content.append(details);
  [['adminRides',data.rides],['adminSupport',data.tickets],['adminIncidents',data.incidents]].forEach(([key,items])=>{const title=element('div','admin-section-title');title.append(element('h3','',t(key)),element('span','',items.length));content.append(title);items.slice(0,5).forEach((row)=>content.append(element('p','',`#${row.id} · ${row.status} · ${localizedDate(row.started_at||row.created_at)}`)));});
  if(can('users.manage')){const access=element('button','button danger',user.status==='active'?t('adminSuspended'):t('adminActive'));access.addEventListener('click',()=>{dialog.close();const spec=quickControlSpec(user.status==='active'?'user.suspend':'user.reactivate');spec.initial.targetId=id;openControlAction(spec);});content.append(access);}
  showCustomDialog(t('adminUsers'),content);
}
function openControlAction(spec){openForm(t('adminStrongAction'),spec.fields,spec.initial,async(values)=>{const payload=spec.payload(values);await api('/api/admin/control-center/actions',{method:'POST',body:JSON.stringify(payload)});});}
function quickControlSpec(actionName){const targetActions=!['service.maintenance','service.restore','mission.create','notification.send','entitlement.grant'].includes(actionName);const definitions={
  'bike.move':[{name:'stationId',label:'adminStation',type:'number',required:true},{name:'dockId',label:'adminDocks',type:'number',required:true}],
  'dock.correct':[{name:'status',label:'adminStatus',type:'select',options:['available','maintenance','disabled'].map((value)=>[value,value])}],
  'maintenance.assign':[{name:'userId',label:'adminAssigned',type:'number',required:true}],
  'mission.create':[{name:'missionType',label:'adminCategory',type:'select',options:['inspection','maintenance','rebalancing','intervention','recovery'].map((value)=>[value,value])},{name:'title',label:'adminSubject',required:true},{name:'priority',label:'adminPriority',type:'select',options:['low','normal','high','urgent'].map((value)=>[value,value])},{name:'userId',label:'adminAssigned',type:'number'},{name:'sourceStationId',label:'adminDeparture',type:'number'},{name:'destinationStationId',label:'adminArrival',type:'number'},{name:'dueAt',label:'adminDue',type:'datetime-local'}],
  'notification.send':[{name:'userId',label:'adminUser',type:'number',required:true},{name:'title',label:'adminSubject',required:true},{name:'message',label:'adminMessage',type:'textarea',wide:true,required:true}],
  'device.status':[{name:'status',label:'adminStatus',type:'select',options:['online','offline','maintenance','disabled'].map((value)=>[value,value])}],
  'automation.toggle':[{name:'enabled',label:'adminActive',type:'checkbox'}],
  'entitlement.grant':[{name:'userId',label:'adminUser',type:'number',required:true},{name:'benefitType',label:'adminBenefit',type:'select',options:[['ride_access','ride_access'],['subscription_extension','subscription_extension'],['service_credit','service_credit']]},{name:'planId',label:'adminPlan',type:'number'},{name:'days',label:'adminDuration',type:'number',min:1,max:366,required:true}]
};const dataFields=definitions[actionName]||[];const fields=[...(targetActions?[{name:'targetId',label:'ID',type:'number',required:true}]:[]),...dataFields,{name:'reason',label:'adminReason',type:'textarea',wide:true,required:true,minLength:10,maxLength:500},{name:'confirmation',label:`PIKALA ${actionName.toUpperCase()}`,wide:true,required:true}];return{action:actionName,targetId:null,fields,initial:{priority:'normal',missionType:'intervention',benefitType:'ride_access',days:30},payload(values){return{action:actionName,targetId:targetActions?values.targetId:null,reason:values.reason,confirmation:values.confirmation,idempotencyKey:crypto.randomUUID(),data:Object.fromEntries(dataFields.map((field)=>[field.name,values[field.name]]))};}};}
function controlCommandBar(){const bar=element('section','admin-command-bar');const copy=element('div');copy.append(element('strong','',t('adminTakeControl')),element('span','',t('adminTakeControlHint')));const controls=element('div');const select=element('select');const actions=['station.open','station.close','bike.block','bike.restore','bike.maintenance','bike.move','dock.correct','user.suspend','user.reactivate','ride.force_end','maintenance.assign','mission.create','notification.send','service.maintenance','service.restore','alert.acknowledge','alert.resolve','automation.toggle','device.status','entitlement.grant','entitlement.revoke'];actions.filter((value)=>can(ACTION_PERMISSIONS[value])).forEach((value)=>select.append(new Option(value.replaceAll('.',' · '),value)));if(!select.options.length)return element('div');const launch=element('button','button primary',t('adminOpenCommand'));launch.type='button';launch.prepend(icon('shield-alert'));launch.addEventListener('click',()=>openControlAction(quickControlSpec(select.value)));controls.append(select,launch);bar.append(copy,controls);return bar;}

function showCustomDialog(title,content){document.querySelector('[data-dialog-title]').textContent=title;document.querySelector('[data-dialog-content]').replaceChildren(content);dialog.showModal();refreshIcons();}
async function stationDialog(id){const data=await api(`/api/admin/stations/${id}`);const s=data.station;openForm(t('adminStations'),stationFields,{name:s.name,publicCode:s.public_code,slug:s.slug,city:s.city,address:s.address,latitude:s.latitude,longitude:s.longitude,capacity:s.capacity,dockCount:s.dock_count,isActive:Boolean(s.is_active),openingHours:s.openingHours},(values)=>api(`/api/admin/stations/${id}`,{method:'PATCH',body:JSON.stringify(normalizeStation(values))}));const mapHost=element('div','admin-station-map');document.querySelector('[data-dialog-content] .admin-form')?.prepend(mapHost);if(window.L){const map=window.L.map(mapHost,{zoomControl:true,scrollWheelZoom:false,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false}).setView([Number(s.latitude),Number(s.longitude)],15);window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);window.L.marker([Number(s.latitude),Number(s.longitude)]).addTo(map).bindTooltip(s.name).openTooltip();setTimeout(()=>map.invalidateSize(),80);}}
async function disableStation(item){const spec=quickControlSpec('station.close');spec.initial.targetId=item.id;openControlAction(spec);}
async function bikeDialog(id){const data=await api(`/api/admin/bikes/${id}`);const bike=data.bike;const content=element('div');const details=element('div','admin-detail-grid');[['adminCode',bike.public_code],['adminStatus',bike.status],['adminStation',bike.station_name||'—'],['adminModel',bike.model||'—'],['adminSerial',bike.serial_number||'—'],['adminLastLogin',localizedDate(bike.last_ride_at,true)]].forEach(([key,value])=>{const item=element('div');item.append(element('span','',t(key)),element('strong','',value));details.append(item);});content.append(details);const actions=element('div','admin-form-actions');const edit=element('button','button secondary',t('adminEdit'));edit.addEventListener('click',()=>{dialog.close();openForm(t('adminBikes'),bikeFields.filter((field)=>!['stationId','status'].includes(field.name)),{publicCode:bike.public_code,code:bike.code,model:bike.model,serialNumber:bike.serial_number,batteryLevel:bike.battery_level},(values)=>api(`/api/admin/bikes/${id}`,{method:'PATCH',body:JSON.stringify(values)}));});const qr=element('button','button secondary',t('adminQr'));qr.addEventListener('click',()=>showQr(id));const maintenance=element('button','button primary',t('adminMaintenanceStart'));maintenance.disabled=bike.status==='in_use'||Number(bike.open_maintenance)>0;maintenance.addEventListener('click',()=>{dialog.close();const spec=quickControlSpec('bike.maintenance');spec.initial.targetId=id;openControlAction(spec);});actions.append(edit,qr,maintenance);content.append(actions);showCustomDialog(t('adminBikes'),content);}
async function showQr(id){const data=await api(`/api/admin/bikes/${id}/qr`);const qr=qrcode(0,'M');qr.addData(data.payload);qr.make();const label=element('div','admin-qr-label');const image=element('img');image.src=qr.createDataURL(6,4);image.alt=`QR ${data.publicCode}`;label.append(image,element('strong','',data.publicCode),element('code','',data.payload));const print=element('button','button primary',t('adminPrint'));print.addEventListener('click',()=>window.print());label.append(print);showCustomDialog(t('adminQr'),label);}
async function rideDialog(id){const data=await api(`/api/admin/rides/${id}`);const content=element('div','admin-detail-grid');Object.entries(data.ride).filter(([,value])=>value!==null).forEach(([key,value])=>{const item=element('div');item.append(element('span','',key.replaceAll('_',' ')),element('strong','',key.endsWith('_at')?localizedDate(value,true):value));content.append(item);});showCustomDialog(t('adminRides'),content);}
function planDialog(item){openForm(t('adminPlans'),planFields,{slug:item.slug,name:item.name,description:item.description,amountMinor:item.amountMinor,currency:item.currency,durationDays:item.durationDays,billingPeriod:item.billingPeriod,status:item.status,displayOrder:item.displayOrder,featured:item.featured,benefitsText:(item.benefits||[]).join('\n')},(data)=>api(`/api/admin/plans/${item.id}`,{method:'PATCH',body:JSON.stringify({...data,benefits:data.benefitsText.split('\n').map((x)=>x.trim()).filter(Boolean),translations:item.translations||{}})}));}
function detailGrid(entries){const grid=element('div','admin-detail-grid');entries.filter(([,value])=>value!==undefined&&value!==null).forEach(([label,value])=>{const cell=element('div');cell.append(element('span','',label.startsWith('admin')?t(label):label),element('strong','',String(value)));grid.append(cell);});return grid;}
function workflowTimeline(events=[]){const list=element('ol','admin-workflow-timeline');events.forEach((event)=>{const item=element('li');item.append(element('strong','',String(event.to_status).replaceAll('_',' ')),element('time','',localizedDate(event.created_at,true)));if(event.note)item.append(element('p','',event.note));list.append(item);});if(!events.length)list.append(element('li','admin-empty',t('adminEmpty')));return list;}
async function workflowDialog(type,item){
  if(type==='maintenance')return maintenanceWorkflow(item);
  const data=await api(`/api/admin/${type==='incident'?'incidents':'support'}/${item.id}`);const content=element('div','admin-operation-detail');
  if(type==='incident'){const incident=data.incident;content.append(detailGrid([['adminReference',incident.public_code],['adminBike',incident.bike_code],['adminCategory',incident.incident_type],['adminSeverity',incident.severity],['adminStatus',incident.status],['adminUser',incident.reporter_email],['adminStation',incident.station_name||'—']]));content.append(element('p','admin-operation-description',incident.description));content.append(element('h3','',t('adminHistory')),workflowTimeline(data.events));const edit=element('button','button primary',t('adminEdit'));edit.addEventListener('click',()=>{dialog.close();openForm(t('adminIncidents'),[{name:'status',label:'adminStatus',type:'select',options:['open','triaged','in_progress','resolved','closed'].map((x)=>[x,x])},{name:'assignedToUserId',label:'Admin ID',type:'number'},{name:'resolutionNotes',label:'adminResolution',type:'textarea',wide:true},{name:'sendToMaintenance',label:'adminMaintenanceStart',type:'checkbox'}],{status:incident.status,assignedToUserId:incident.assigned_to_user_id,resolutionNotes:incident.resolution_notes||'',sendToMaintenance:false},async(values)=>{if(values.sendToMaintenance&&!await confirmAction(t('adminSensitiveConfirm')))return;await api(`/api/admin/incidents/${incident.id}`,{method:'PATCH',body:JSON.stringify(values)});});});content.append(edit);showCustomDialog(t('adminIncidents'),content);return;}
  const ticket=data.ticket;content.append(detailGrid([['adminReference',ticket.public_code],['adminUser',ticket.user_email||ticket.email],['adminCategory',ticket.topic],['adminPriority',ticket.priority],['adminStatus',ticket.status],['adminBike',ticket.bike_code||'—'],['adminStation',ticket.station_name||'—']]));content.append(element('p','admin-operation-description',ticket.message));const messages=element('div','admin-message-list');messages.append(element('h3','',t('adminMessages')));data.messages.forEach((message)=>{const row=element('article',`admin-message is-${message.author_kind}`);row.append(element('strong','',message.author_kind==='admin'?t('adminConsole'):message.author_kind),element('time','',localizedDate(message.created_at,true)),element('p','',message.body));messages.append(row);});content.append(messages,element('h3','',t('adminHistory')),workflowTimeline(data.events));if(!['resolved','closed'].includes(ticket.status)){const reply=element('form','admin-reply-form');const textarea=element('textarea');textarea.name='message';textarea.required=true;textarea.minLength=2;textarea.maxLength=4000;textarea.placeholder=t('adminReplyPlaceholder');const send=element('button','button primary',t('adminReply'));send.type='submit';reply.append(textarea,send);reply.addEventListener('submit',async(event)=>{event.preventDefault();send.disabled=true;try{await api(`/api/admin/support/${ticket.id}/messages`,{method:'POST',body:JSON.stringify({message:textarea.value})});dialog.close();showToast(t('adminReplySent'));await loadView();}catch(error){showToast(error.message,{tone:'error'});send.disabled=false;}});content.append(reply);}const edit=element('button','button secondary',t('adminEdit'));edit.addEventListener('click',()=>{dialog.close();openForm(t('adminSupport'),[{name:'status',label:'adminStatus',type:'select',options:['open','in_progress','waiting_user','resolved','closed'].map((x)=>[x,x])},{name:'priority',label:'adminPriority',type:'select',options:['low','normal','high','urgent'].map((x)=>[x,x])},{name:'assignedToUserId',label:'Admin ID',type:'number'},{name:'resolutionNotes',label:'adminResolution',type:'textarea',wide:true}],{status:ticket.status,priority:ticket.priority,assignedToUserId:ticket.assigned_to_user_id,resolutionNotes:ticket.resolution_notes||''},async(values)=>{if(['resolved','closed'].includes(values.status)&&!await confirmAction(t('adminSensitiveConfirm')))return;await api(`/api/admin/support/${ticket.id}`,{method:'PATCH',body:JSON.stringify(values)});});});content.append(edit);showCustomDialog(t('adminSupport'),content);
}
function maintenanceWorkflow(item){const stages=['reported','to_inspect','maintenance','repaired','available'];openForm(t('adminMaintenance'),[{name:'workflowStage',label:'adminStatus',type:'select',options:stages.map((stage)=>[stage,`adminStage_${stage}`])},{name:'assignedToUserId',label:'Admin ID',type:'number'},{name:'resolutionNotes',label:'adminResolution',type:'textarea',wide:true}],{workflowStage:item.workflow_stage||'to_inspect',assignedToUserId:item.assigned_to_user_id,resolutionNotes:''},async(values)=>{if(values.workflowStage==='available'&&!await confirmAction(t('adminMaintenanceConfirm')))return;await api(`/api/admin/maintenance/${item.id}`,{method:'PATCH',body:JSON.stringify(values)});});}
function notificationForm(){openForm(t('adminNotifications'),[{name:'title',label:'adminSubject',required:true},{name:'body',label:'adminMessage',type:'textarea',wide:true,required:true},{name:'type',label:'adminCategory'},{name:'target',label:'adminTarget',type:'select',options:[['active','Actifs'],['all','Tous'],['users','IDs utilisateurs']]},{name:'locale',label:'adminLocale',type:'select',options:[['all','Toutes'],['fr','FR'],['en','EN'],['es','ES'],['pt','PT'],['ar','AR']]},{name:'userIdsText',label:'IDs (séparés par virgule)',wide:true},{name:'reason',label:'adminReason',type:'textarea',wide:true,required:true,minLength:10,maxLength:500},{name:'confirmation',label:'PIKALA NOTIFICATION.SEND',wide:true,required:true}],{type:'service',target:'active',locale:'all'},async(values)=>{if(!await confirmAction(t('adminBroadcastConfirm')))return;await api('/api/admin/notifications',{method:'POST',body:JSON.stringify({...values,idempotencyKey:crypto.randomUUID(),userIds:values.userIdsText.split(',').map((x)=>Number(x.trim())).filter(Number.isInteger)})});});}

async function renderSettings(){const data=await api('/api/admin/settings');const grid=element('div','admin-settings');data.settings.forEach((setting)=>{const card=element('article','admin-setting');card.append(element('h2','',setting.key.replaceAll('_',' ')),element('p','',setting.description||''));const form=element('form');const textarea=element('textarea');textarea.className='admin-form';textarea.value=JSON.stringify(setting.value,null,2);const save=element('button','button primary',t('adminSave'));save.type='submit';form.append(textarea,save);form.addEventListener('submit',async(event)=>{event.preventDefault();try{const value=JSON.parse(textarea.value);await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify({key:setting.key,value})});showToast(t('adminSave'));}catch(error){showToast(error.message,{tone:'error'});}});card.append(form);grid.append(card);});host.replaceChildren(grid);host.setAttribute('aria-busy','false');}

async function loadView(){if(!canView(state.view)){const fallback=NAV.flatMap(([,items])=>items).find(([view])=>canView(view))?.[0]||'dashboard';return navigate(fallback,{replace:true});}document.querySelector('[data-admin-heading]').textContent=viewLabel(state.view);loading();try{if(state.view==='dashboard'||state.view==='system')await renderDashboard();else if(state.view==='settings')await renderSettings();else await renderList(state.view);}catch(error){if(error.status===401)location.assign('/connexion.html?next=/admin.html');else if(error.status===403)location.assign('/dashboard.html?access=denied');else errorState(error);}}

document.querySelector('[data-admin-menu]').addEventListener('click',()=>{document.querySelector('[data-admin-sidebar]').classList.toggle('is-open');document.querySelector('[data-admin-backdrop]').classList.toggle('is-open');});document.querySelector('[data-admin-backdrop]').addEventListener('click',closeSidebar);addEventListener('popstate',()=>{state.view=new URLSearchParams(location.search).get('view')||'dashboard';mountNav();loadView();});document.addEventListener('pikala:localechange',()=>{mountNav();document.querySelector('[data-admin-heading]').textContent=viewLabel(state.view);translateDocument();if(state.data)loadView();});

initLayout();refreshIcons();if(await requireAdmin()){if(!canView(state.view))state.view=NAV.flatMap(([,items])=>items).find(([view])=>canView(view))?.[0]||'dashboard';mountNav();loadView();}
