import {getLocale,initI18n,setLocale,t,translateDocument} from './assets/js/i18n/index.js';

const content=document.querySelector('[data-workshop-content]');const dialog=document.querySelector('[data-workshop-dialog]');const dialogBody=document.querySelector('[data-dialog-body]');let overview=null;let parts=[];let activeTab='missions';
const CHECKS=['brakes','tires','wheels','chain','saddle','lighting','frame','qr','lock','electronics'];
const CHECK_LABELS={brakes:'Freins',tires:'Pneus',wheels:'Roues',chain:'Chaîne',saddle:'Selle',lighting:'Éclairage',frame:'Cadre',qr:'QR',lock:'Serrure',electronics:'Électronique'};
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node;}
async function api(path,options={}){let response;try{response=await fetch(path,{...options,credentials:'same-origin',headers:{'content-type':'application/json','x-pikala-request':'web',...(options.headers||{})}});}catch{throw new Error(t('workshopError'));}const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||t('workshopError'));error.status=response.status;throw error;}return data;}
function loading(){content.setAttribute('aria-busy','true');const state=el('div','pk-state');state.append(el('span','pk-loader'),el('p','',t('workshopLoading')));content.replaceChildren(state);}
function empty(){const state=el('div','pk-state');state.append(el('h2','pk-state__title',t('workshopEmpty')));return state;}
function errorState(error){const state=el('div','pk-state pk-state--error');state.append(el('h2','pk-state__title',t('workshopError')),el('p','',error.message));content.replaceChildren(state);content.setAttribute('aria-busy','false');}
function stage(value){return t(`workshopStage_${value}`);}
function card(title,subtitle,badge,action){const node=el('article','workshop-card');node.append(el('h2','',title),el('p','',subtitle||''));const meta=el('div','workshop-meta');meta.append(el('span','workshop-stage',badge));if(action){const button=el('button','pk-button pk-button--primary',t('workshopOpen'));button.type='button';button.addEventListener('click',action);meta.append(button);}node.append(meta);return node;}
function grid(items){if(!items.length)return empty();const node=el('div','workshop-grid');items.forEach(item=>node.append(item));return node;}
async function refresh(){loading();try{overview=await api('/api/admin/workshop/overview');parts=(await api('/api/admin/workshop/parts')).items||[];await render();}catch(error){if(error.status===401)location.assign(`/connexion.html?next=${encodeURIComponent('/atelier.html')}`);else if(error.status===403)location.assign('/dashboard.html?access=denied');else errorState(error);}}
async function render(){if(activeTab==='interventions'){const data=await api('/api/admin/workshop/interventions');content.replaceChildren(grid(data.items.map(item=>card(item.bike_code,item.problem_text,stage(item.workshop_stage),()=>openIntervention(item.id)))));}else if(activeTab==='missions'){content.replaceChildren(grid((overview.missions||[]).map(item=>card(item.public_code,item.title,`${item.priority} · ${item.status}`,null))));}else if(activeTab==='parts'){content.replaceChildren(grid(parts.map(item=>card(`${item.reference} · ${item.name}`,item.supplier||item.category,item.stock_quantity==null?'∞':item.stock_quantity,null))));}else{content.replaceChildren(grid((overview.reminders||[]).map(item=>card(item.bike_code,item.reason,item.trigger_type,null))));}content.setAttribute('aria-busy','false');}
function field(label,type='textarea'){const wrap=el('label','pk-field');wrap.append(el('span','',label));const input=el(type==='select'?'select':type==='input'?'input':'textarea',type==='select'?'pk-select':type==='input'?'pk-input':'pk-textarea');wrap.append(input);return{wrap,input};}
function submitButton(label=t('workshopSave')){const button=el('button','pk-button pk-button--primary',label);button.type='submit';return button;}
async function sendTransition(id,stageValue,body={}){await api(`/api/admin/workshop/interventions/${id}/transition`,{method:'POST',body:JSON.stringify({stage:stageValue,...body})});dialog.close();await refresh();}
function inspectionForm(id){const form=el('form','workshop-form');form.append(el('h3','',t('workshopInspection')));const checklist=el('div','checklist');for(const code of CHECKS){const item=field(CHECK_LABELS[code],'select');item.input.name=code;for(const [value,label] of [['pass',t('workshopPass')],['watch',t('workshopWatch')],['fail',t('workshopFail')],['not_applicable',t('workshopNotApplicable')]]){const option=el('option','',label);option.value=value;item.input.append(option);}checklist.append(item.wrap);}form.append(checklist,submitButton());form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{const data=new FormData(form);const result=await api('/api/admin/workshop/inspections',{method:'POST',body:JSON.stringify({maintenanceId:id,items:CHECKS.map(code=>({code,result:data.get(code)}))})});alert(`${t('workshopHealth')} : ${result.healthScore}/100`);await openIntervention(id);}catch(error){alert(error.message);button.disabled=false;}});return form;}
function transitionForm(record,data){const next=data.nextStage;if(!next)return null;const form=el('form','workshop-form');form.append(el('h3','',`${t('workshopNext')} : ${stage(next)}`));let diagnosis,notes,testNotes,confirm;
  if(next==='diagnosed'){const item=field(t('workshopDiagnosis'));diagnosis=item.input;diagnosis.required=true;form.append(item.wrap);}
  if(next==='testing'){const item=field(t('workshopWork'));notes=item.input;notes.required=true;form.append(item.wrap);}
  if(next==='repaired'){const item=field(t('workshopTest'));testNotes=item.input;testNotes.required=true;form.append(item.wrap);}
  if(next==='available'){const label=el('label','pk-checkbox');confirm=el('input');confirm.type='checkbox';confirm.required=true;label.append(confirm,el('span','',t('workshopRelease')));form.append(label);}
  form.append(submitButton(next==='available'?t('workshopRelease'):t('workshopNext')));form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await sendTransition(record.id,next,{diagnosis:diagnosis?.value,notes:notes?.value,testResult:next==='repaired'?'passed':undefined,testNotes:testNotes?.value,confirmReturnToService:confirm?.checked===true});}catch(error){alert(error.message);button.disabled=false;}});return form;
}
function partForm(record){if(!['diagnosed','maintenance'].includes(record.workshop_stage)||!parts.length)return null;const form=el('form','workshop-form');form.append(el('h3','',t('workshopPart')));const part=field(t('workshopParts'),'select');parts.forEach(item=>{const option=el('option','',`${item.reference} · ${item.name} (${item.stock_quantity??'∞'})`);option.value=item.id;part.input.append(option);});const quantity=field(t('workshopQuantity'),'input');quantity.input.type='number';quantity.input.min='1';quantity.input.value='1';form.append(part.wrap,quantity.wrap,submitButton());form.addEventListener('submit',async event=>{event.preventDefault();try{await api(`/api/admin/workshop/interventions/${record.id}/parts`,{method:'POST',body:JSON.stringify({partId:Number(part.input.value),quantity:Number(quantity.input.value)})});await openIntervention(record.id);}catch(error){alert(error.message);}});return form;}
function commentForm(record){const form=el('form','workshop-form');const message=field(t('workshopComment'));message.input.required=true;form.append(message.wrap,submitButton());form.addEventListener('submit',async event=>{event.preventDefault();try{await api(`/api/admin/workshop/interventions/${record.id}/comments`,{method:'POST',body:JSON.stringify({message:message.input.value})});await openIntervention(record.id);}catch(error){alert(error.message);}});return form;}
async function openIntervention(id){try{const data=await api(`/api/admin/workshop/interventions/${id}`);const record=data.intervention;document.querySelector('[data-dialog-title]').textContent=`${record.bike_code} · ${stage(record.workshop_stage)}`;const body=el('div');const summary=el('div','workshop-summary');[['Priorité',record.priority],['Temps',`${record.labor_minutes} min`],['Coût',`${(record.total_cost_minor/100).toFixed(2)} MAD`]].forEach(([label,value])=>{const item=el('div');item.append(el('span','',label),el('strong','',value));summary.append(item);});body.append(summary,el('p','',record.problem_text||record.reason));if(record.workshop_stage==='reported'){const button=el('button','pk-button pk-button--primary',`${t('workshopNext')} : ${stage('inspection_required')}`);button.addEventListener('click',()=>sendTransition(id,'inspection_required'));body.append(button);}else if(record.workshop_stage==='inspection_required'&&!data.inspections.length)body.append(inspectionForm(id));else{const form=transitionForm(record,data);if(form)body.append(form);}const usage=partForm(record);if(usage)body.append(usage);body.append(commentForm(record));const history=el('ol','history');data.events.forEach(event=>{const item=el('li','',`${stage(event.to_status)} · ${new Date(event.created_at+'Z').toLocaleString(getLocale())}`);if(event.note)item.append(el('p','',event.note));history.append(item);});body.append(history);dialogBody.replaceChildren(body);dialog.showModal();}catch(error){alert(error.message);}}

document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',async()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('is-active',item===button));activeTab=button.dataset.tab;await render();}));document.querySelector('[data-locale]').addEventListener('change',event=>{setLocale(event.target.value);render();});document.addEventListener('pikala:localechange',()=>{document.querySelector('[data-locale]').value=getLocale();translateDocument();});initI18n();document.querySelector('[data-locale]').value=getLocale();const requestedIntervention=Number(new URLSearchParams(location.search).get('intervention'));if(Number.isInteger(requestedIntervention)&&requestedIntervention>0){activeTab='interventions';document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('is-active',item.dataset.tab==='interventions'));await refresh();await openIntervention(requestedIntervention);}else await refresh();
