import {getLocale,initI18n,setLocale,t,translateDocument} from './assets/js/i18n/index.js';

const content=document.querySelector('[data-content]');const stats=document.querySelector('[data-stats]');const taskDialog=document.querySelector('[data-task-dialog]');const taskBody=document.querySelector('[data-task-body]');const scanner=document.querySelector('[data-scanner-dialog]');const scanForm=document.querySelector('[data-scan-form]');const video=document.querySelector('[data-video]');const adminTools=document.querySelector('[data-admin-tools]');const suggestionsHost=document.querySelector('[data-suggestions]');const adminDialog=document.querySelector('[data-admin-dialog]');const adminForm=document.querySelector('[data-admin-form]');
let tasks=[];let overview={};let activeTab='missions';let activeTask=null;let scanType=null;let scanControls=null;let manager=false;
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node;}
async function api(path,options={}){let response;try{response=await fetch(path,{...options,credentials:'same-origin',headers:{'content-type':'application/json','x-pikala-request':'web',...(options.headers||{})}});}catch{throw new Error(t('fieldError'));}const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||t('fieldError'));error.status=response.status;error.code=data.code;throw error;}return data;}
function loading(){content.setAttribute('aria-busy','true');const state=el('div','pk-state');state.append(el('span','pk-loader'),el('p','',t('fieldLoading')));content.replaceChildren(state);}
function status(value){return t(`fieldStatus_${value}`);}
function stat(value,label){const node=el('article','field-stat');node.append(el('strong','',value||0),el('span','',label));return node;}
function renderStats(){stats.replaceChildren(stat((overview.counts?.assigned||0)+(overview.counts?.accepted||0),t('fieldAssigned')),stat(overview.inCustody,t('fieldOnBoard')),stat(overview.overdue,t('fieldOverdue')));}
function taskCard(item){const card=el('article',`field-card${item.priority==='urgent'?' is-urgent':''}`);const head=el('div','field-card-head');head.append(el('span','field-badge',item.public_code),el('span','field-badge',status(item.status)));card.append(head,el('h2','',item.description),el('p','field-route',`${t('fieldFrom')} : ${item.source_station||'—'} · ${t('fieldTo')} : ${item.destination_station||'—'}`));const actions=el('div','field-actions');actions.append(el('span','',`${item.bike_count||0} ${t('fieldBikes')}`));const open=el('button','pk-button pk-button--primary',t('fieldOpen'));open.type='button';open.addEventListener('click',()=>openTask(item.id));actions.append(open);card.append(actions);return card;}
function render(){let visible=tasks;if(activeTab==='active')visible=tasks.filter(item=>['accepted','in_progress'].includes(item.status));if(activeTab==='custody')visible=tasks.filter(item=>Number(item.custody_count)>0);if(!visible.length){const empty=el('div','pk-state');empty.append(el('h2','pk-state__title',t('fieldEmpty')));content.replaceChildren(empty);}else{const list=el('div','field-list');visible.forEach(item=>list.append(taskCard(item)));content.replaceChildren(list);}content.setAttribute('aria-busy','false');}
async function refresh(){loading();try{[overview,{items:tasks}]=await Promise.all([api('/api/admin/field/overview'),api('/api/admin/field/tasks?limit=100')]);renderStats();render();if(manager)await loadSuggestions();}catch(error){if(error.status===401)location.assign(`/connexion.html?next=${encodeURIComponent('/terrain.html')}`);else if(error.status===403)location.assign('/dashboard.html?access=denied');else{const state=el('div','pk-state pk-state--error');state.append(el('h2','pk-state__title',t('fieldError')),el('p','',error.message));content.replaceChildren(state);}}}
function actionButton(label,handler,secondary=false){const button=el('button',`pk-button ${secondary?'pk-button--ghost':'pk-button--primary'}`,label);button.type='button';button.addEventListener('click',async()=>{button.disabled=true;try{await handler();}catch(error){alert(error.message);button.disabled=false;}});return button;}
async function transition(id,next){await api(`/api/admin/field/tasks/${id}/transition`,{method:'POST',body:JSON.stringify({status:next})});await refresh();await openTask(id);}
function completedScan(detail,type){return detail.scans.some(scan=>scan.scan_type===type);}
function step(label,done,action){const item=el('li',`field-step${done?' is-done':''}`);item.append(el('span','field-step-index',done?'✓':'•'),el('strong','',label));if(!done&&action)item.append(actionButton(t('fieldScan'),action,true));return item;}
function bikeList(detail){const panel=el('section','field-panel');panel.append(el('h3','',t('fieldBikes')));if(!detail.bikes.length){panel.append(el('p','',t('fieldNoBike')));return panel;}detail.bikes.forEach(bike=>{const row=el('div','bike-row');row.append(el('strong','',bike.public_code),el('span','field-badge',bike.custody_status));panel.append(row);});return panel;}
async function openTask(id){const detail=await api(`/api/admin/field/tasks/${id}`);activeTask=detail;document.querySelector('[data-task-title]').textContent=detail.task.public_code;const root=el('div','field-detail');root.append(el('p','',detail.task.description),el('p','field-route',`${t('fieldFrom')} : ${detail.task.source_station||'—'} · ${t('fieldTo')} : ${detail.task.destination_station||'—'}`));const actions=el('div','field-actions');if(detail.task.status==='assigned')actions.append(actionButton(t('fieldAccept'),()=>transition(id,'accepted')));if(detail.task.status==='accepted')actions.append(actionButton(t('fieldStart'),()=>transition(id,'in_progress')));if(detail.task.status==='in_progress')actions.append(actionButton(t('fieldComplete'),()=>transition(id,'completed')));if(actions.children.length)root.append(actions);
  if(detail.task.status==='in_progress'){const steps=el('ol','field-step-list');const sourceDone=completedScan(detail,'source_station');const destinationDone=completedScan(detail,'destination_station');const allPicked=detail.bikes.length>0&&detail.bikes.every(bike=>['picked_up','deposited'].includes(bike.custody_status));const allDeposited=detail.bikes.length>0&&detail.bikes.every(bike=>bike.custody_status==='deposited');steps.append(step(t('fieldSourceScan'),sourceDone,()=>openScanner('source_station')),step(t('fieldPickupScan'),allPicked,sourceDone?()=>openScanner('pickup_bike'):null),step(t('fieldDestinationScan'),destinationDone,allPicked?()=>openScanner('destination_station'):null),step(t('fieldDepositScan'),allDeposited,destinationDone?()=>openScanner('deposit_bike'):null));root.append(steps);}
  root.append(bikeList(detail));const history=el('section','field-panel');history.append(el('h3','',t('fieldHistory')));const list=el('ol','field-history');detail.events.forEach(event=>list.append(el('li','',`${event.event_type} · ${new Date(`${event.created_at}Z`).toLocaleString(getLocale())}`)));history.append(list);root.append(history);taskBody.replaceChildren(root);if(!taskDialog.open)taskDialog.showModal();}
async function openScanner(type){scanType=type;scanForm.reset();document.querySelector('[data-bike-code]').hidden=type!=='deposit_bike';document.querySelector('[data-scan-message]').textContent='';scanner.showModal();try{if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia||!window.ZXingBrowser?.BrowserQRCodeReader)throw new Error();const reader=new window.ZXingBrowser.BrowserQRCodeReader();scanControls=await reader.decodeFromVideoDevice(undefined,video,(result,_error,controls)=>{if(!result)return;scanForm.elements.code.value=result.getText();controls.stop();scanControls=null;scanForm.elements.code.focus();});}catch{document.querySelector('[data-scan-message]').textContent=t('fieldCameraError');}}
function closeScanner(){scanControls?.stop();scanControls=null;if(video.srcObject)video.srcObject.getTracks().forEach(track=>track.stop());video.srcObject=null;scanner.close();}
scanForm.addEventListener('submit',async event=>{event.preventDefault();const message=document.querySelector('[data-scan-message]');message.classList.remove('is-error');const submit=scanForm.querySelector('button');submit.disabled=true;try{await api(`/api/admin/field/tasks/${activeTask.task.id}/scan`,{method:'POST',body:JSON.stringify({type:scanType,code:scanForm.elements.code.value,dockCode:scanType==='deposit_bike'?scanForm.elements.code.value:undefined,bikeCode:scanType==='deposit_bike'?scanForm.elements.bikeCode.value:undefined,idempotencyKey:crypto.randomUUID()})});message.textContent=t('fieldScanSuccess');closeScanner();await refresh();await openTask(activeTask.task.id);}catch(error){message.textContent=error.message;message.classList.add('is-error');submit.disabled=false;}});
function suggestionCard(item){const card=el('article','field-suggestion');const copy=el('div');copy.append(el('strong','',`${item.source_station} → ${item.destination_station}`),el('p','',item.reason),el('span','field-badge',`${item.suggested_bikes} ${t('fieldBikes')}`));const actions=el('div','field-actions');actions.append(actionButton(t('fieldAccept'),async()=>{const count=Number(prompt(t('fieldBikeCount'),item.suggested_bikes));if(!Number.isInteger(count)||count<1)return;const agentValue=prompt(t('fieldAgentId'),'');const agentId=agentValue?Number(agentValue):null;await api(`/api/admin/field/rebalancing/${item.id}`,{method:'POST',body:JSON.stringify({action:'accept',bikeCount:count,agentId})});await refresh();}),actionButton(t('fieldIgnore'),async()=>{const reason=prompt(t('fieldIgnoreReason'));if(!reason)return;await api(`/api/admin/field/rebalancing/${item.id}`,{method:'POST',body:JSON.stringify({action:'ignore',reason})});await loadSuggestions();},true));card.append(copy,actions);return card;}
async function loadSuggestions(){const data=await api('/api/admin/field/rebalancing');suggestionsHost.hidden=!data.items.length;suggestionsHost.replaceChildren(...data.items.map(suggestionCard));}
async function setupManager(){const session=await api('/api/admin/session');manager=session.user.permissions.includes('*')||session.user.permissions.includes('field_tasks.manage');adminTools.hidden=!manager;if(manager)await loadSuggestions();}
document.querySelector('[data-generate]').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await api('/api/admin/field/rebalancing/generate',{method:'POST',body:'{}'});await loadSuggestions();}catch(error){alert(error.message);}finally{event.currentTarget.disabled=false;}});document.querySelector('[data-new-task]').addEventListener('click',()=>adminDialog.showModal());document.querySelector('[data-admin-close]').addEventListener('click',()=>adminDialog.close());adminForm.addEventListener('submit',async event=>{event.preventDefault();const submit=adminForm.querySelector('button[type="submit"]');submit.disabled=true;const data=Object.fromEntries(new FormData(adminForm));const number=name=>data[name]?Number(data[name]):null;try{await api('/api/admin/field/tasks',{method:'POST',body:JSON.stringify({type:data.type,priority:data.priority,description:data.description,agentId:number('agentId'),sourceStationId:number('sourceStationId'),destinationStationId:number('destinationStationId'),bikeIds:String(data.bikeIds||'').split(',').map(value=>Number(value.trim())).filter(Number.isInteger),deadline:data.deadline||null})});adminDialog.close();adminForm.reset();await refresh();}catch(error){alert(error.message);}finally{submit.disabled=false;}});
document.querySelector('[data-close]').addEventListener('click',()=>taskDialog.close());document.querySelector('[data-scan-close]').addEventListener('click',closeScanner);scanner.addEventListener('close',()=>{scanControls?.stop();scanControls=null;});document.querySelector('[data-refresh]').addEventListener('click',refresh);document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{activeTab=button.dataset.tab;document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('is-active',item===button));render();}));document.querySelector('[data-locale]').addEventListener('change',event=>setLocale(event.target.value));document.addEventListener('pikala:localechange',()=>{document.querySelector('[data-locale]').value=getLocale();translateDocument();renderStats();render();});initI18n();document.querySelector('[data-locale]').value=getLocale();await setupManager();await refresh();
