const MODES=new Set(['disabled','test','production']);
const encoder=new TextEncoder();
function base64Url(bytes){let binary='';bytes.forEach(byte=>{binary+=String.fromCharCode(byte);});return btoa(binary).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function fromBase64Url(value){const normalized=String(value).replaceAll('-','+').replaceAll('_','/');const binary=atob(normalized+'='.repeat((4-normalized.length%4)%4));return Uint8Array.from(binary,char=>char.charCodeAt(0));}
async function sha256(value){return base64Url(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))));}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return base64Url(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(value))));}
async function equalHash(left,right){const[a,b]=await Promise.all([crypto.subtle.digest('SHA-256',encoder.encode(String(left))),crypto.subtle.digest('SHA-256',encoder.encode(String(right)))]);return crypto.subtle.timingSafeEqual(a,b);}
async function encryptionKey(raw){if(typeof raw!=='string'||raw.length<32)throw Object.assign(new Error('IoT encryption key unavailable'),{code:'IOT_KEY_UNAVAILABLE'});return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',encoder.encode(raw)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function encryptDeviceSecret(secret,kek){const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(kek),encoder.encode(secret));return{hash:await sha256(secret),ciphertext:base64Url(new Uint8Array(ciphertext)),iv:base64Url(iv)};}
export async function decryptDeviceSecret(record,kek){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64Url(record.secret_iv)},await encryptionKey(kek),fromBase64Url(record.secret_ciphertext));return new TextDecoder().decode(plain);}
export function iotMode(env){const mode=String(env.IOT_MODE||'disabled').toLowerCase();return MODES.has(mode)?mode:'disabled';}
export function createDeviceProvider(env){const mode=iotMode(env);return{name:mode==='test'?'test':String(env.DEVICE_PROVIDER||'unconfigured'),mode,configured:mode==='test'||(mode==='production'&&Boolean(env.DEVICE_PROVIDER)),async sendCommand(command){if(mode==='disabled')throw Object.assign(new Error('IoT disabled'),{code:'IOT_DISABLED'});if(mode==='production')throw Object.assign(new Error('Hardware adapter unavailable'),{code:'DEVICE_PROVIDER_UNAVAILABLE'});return{providerCommandId:`test:${command.command_id}`,status:'sent'};},async getDeviceStatus(device){return{status:device.status,connectivityStatus:device.connectivity_status,lastSeenAt:device.last_seen_at};},async verifyIncomingEvent({raw,signature,secret}){const expected=await hmac(secret,raw);return equalHash(signature,expected);},normalizeTelemetry(payload){const safe={};if(['unknown','online','offline','degraded'].includes(payload?.connectivityStatus))safe.connectivityStatus=payload.connectivityStatus;if(Number.isInteger(payload?.batteryLevel)&&payload.batteryLevel>=0&&payload.batteryLevel<=100)safe.batteryLevel=payload.batteryLevel;if(['unknown','locked','unlocked','jammed','offline'].includes(payload?.lockStatus))safe.lockStatus=payload.lockStatus;for(const key of ['latitude','longitude'])if(Number.isFinite(payload?.[key]))safe[key]=payload[key];return safe;},handleAcknowledgement(payload){const status=String(payload?.status||'');return['acknowledged','completed','failed'].includes(status)?{status,reason:String(payload?.reason||'').slice(0,500)||null}:null;}};}
export function generateDeviceSecret(){return base64Url(crypto.getRandomValues(new Uint8Array(32)));}
