import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import adminCopy from '../sitepikala/assets/js/i18n/admin/copy.js';
const root=resolve(import.meta.dirname,'..');const failures=[];const check=(condition,message)=>{if(!condition)failures.push(message);};
const [worker,service,migration,html,frontend,css]=await Promise.all(['src/worker.js','src/admin/service.js','migrations/0008_admin_operations.sql','sitepikala/admin.html','sitepikala/admin.js','sitepikala/admin.css'].map((file)=>readFile(resolve(root,file),'utf8')));
const views=['dashboard','users','stations','bikes','rides','plans','subscriptions','payments','incidents','maintenance','support','notifications','settings','audit'];
for(const view of views)check(frontend.includes(`'${view}'`)||frontend.includes(`/${view}`),`Vue admin absente: ${view}`);
check(worker.includes("url.pathname.startsWith('/api/admin/')")&&worker.includes("requireRole(request, env, ['admin'])"),'Barriere admin serveur centralisee absente.');
for(const route of ['users','stations','bikes','rides','notifications','settings','audit-logs'])check(service.includes(`/api/admin/${route}`),`Route absente: /api/admin/${route}`);
for(const [route,handler] of Object.entries({incidents:'incidentUpdate',maintenance:'maintenanceUpdate',support:'supportUpdate'}))check(service.includes(`'${route}'`)&&service.includes(`function ${handler}`),`Route absente: /api/admin/${route}`);
check(service.includes('admin_audit_logs')&&service.includes('safeMetadata'),'Audit sensible ou filtrage metadata absent.');
check(!/UPDATE payments SET|INSERT INTO payments|DELETE FROM payments/.test(service),'L administration peut modifier les paiements.');
check(service.includes('LIMIT ? OFFSET ?')&&service.includes('pagination'),'Pagination API absente.');
check(service.includes("id === actor.id")&&service.includes('dernier administrateur'),'Protections contre auto-verrouillage admin absentes.');
check(migration.includes('maintenance_records')&&migration.includes('app_settings'),'Tables operations admin absentes.');
check(!/^[ \t]*(?:DROP|DELETE|TRUNCATE)\b/im.test(migration),'Migration admin destructive.');
check(html.includes('data-admin-nav')&&html.includes('data-admin-view')&&html.includes('noindex,nofollow'),'Coque admin ou noindex absent.');
check(frontend.includes('qrcode(')&&html.includes('leaflet'),'QR ou carte station absente.');
check(html.includes('assets/vendor/leaflet/leaflet.css')&&html.includes('assets/vendor/leaflet/leaflet.js'),'Leaflet local absent.');
check(css.includes('@media(max-width:820px)')&&css.includes('[dir=rtl]'),'Responsive tablette ou RTL admin absent.');
const keys=Object.keys(adminCopy.fr);for(const locale of ['fr','en','es','pt','ar'])check(keys.every((key)=>Object.hasOwn(adminCopy[locale],key)),`${locale}: traductions admin incompletes.`);
if(failures.length){console.error(failures.map((item)=>`- ${item}`).join('\n'));process.exit(1);}console.log(`Administration valide: ${views.length} vues, ${keys.length} cles x 5 langues, API protegee.`);
