import { hasAnyPermission, hasPermission } from '../auth/rbac.js';

const ASSET_TYPES=new Set(['bike','station','dock']);
const BULK_ENTITIES=new Set(['bikes','stations','docks']);
const TABLES={bike:'bikes',station:'stations',dock:'docks'};
const integer=(value)=>{const parsed=Number(value);return Number.isInteger(parsed)&&parsed>0?parsed:null;};
const finite=(value,min,max)=>{const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=min&&parsed<=max?parsed:null;};
const cleanText=(value,min=0,max=240)=>{const result=String(value??'').trim();return result.length>=min&&result.length<=max?result:null;};
const cleanCode=(value)=>{const result=String(value??'').trim();return /^[A-Za-z0-9][A-Za-z0-9._:-]{1,79}$/.test(result)?result:null;};
const fail=(json,code,error,status=400)=>json({code,error},status);
const idsFrom=(value)=>[...new Set((Array.isArray(value)?value:String(value||'').split(',')).map(integer).filter(Boolean))].slice(0,100);

function strong(body,action){const reason=cleanText(body?.reason,10,500);const idempotencyKey=cleanText(body?.idempotencyKey,16,120);return reason&&idempotencyKey&&body?.confirmation===`PIKALA ${action}`?{reason,idempotencyKey}:null;}

function csvRows(source){
  const rows=[];let row=[];let field='';let quoted=false;const input=String(source||'').replace(/^\uFEFF/,'');
  for(let index=0;index<input.length;index+=1){const char=input[index];if(quoted){if(char==='"'&&input[index+1]==='"'){field+='"';index+=1;}else if(char==='"')quoted=false;else field+=char;continue;}if(char==='"'){quoted=true;continue;}if(char===','){row.push(field.trim());field='';continue;}if(char==='\n'){row.push(field.trim());if(row.some(Boolean))rows.push(row);row=[];field='';continue;}if(char!=='\r')field+=char;}
  if(quoted)throw new Error('CSV_UNCLOSED_QUOTE');row.push(field.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)return[];
  const headers=rows[0].map((item)=>item.toLowerCase().replace(/[^a-z0-9_]/g,''));if(headers.some((item,index)=>!item||headers.indexOf(item)!==index))throw new Error('CSV_HEADERS_INVALID');return rows.slice(1,101).map((values)=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??''])));
}

function validateImport(entity,rows){
  const errors=[];const normalized=[];rows.forEach((row,index)=>{const line=index+2;
    if(entity==='bikes'){const publicCode=cleanCode(row.public_code);const internalCode=cleanCode(row.code||String(publicCode||'').toUpperCase());const serial=cleanText(row.serial_number,0,120);const model=cleanText(row.model,0,120);const stationCode=row.station_code?cleanCode(row.station_code):null;const battery=row.battery_level===''?null:finite(row.battery_level,0,100);if(!publicCode||!internalCode||serial===null||model===null||(row.station_code&&!stationCode)||battery===null)errors.push({line,error:'Vélo invalide'});else normalized.push({line,publicCode,internalCode,serial,model,stationCode,battery});}
    else if(entity==='stations'){const publicCode=cleanCode(row.public_code);const name=cleanText(row.name,2,120);const city=cleanText(row.city||'Rabat',2,80);const address=cleanText(row.address,0,240);const latitude=finite(row.latitude,-90,90);const longitude=finite(row.longitude,-180,180);const capacity=Number(row.capacity);const dockCount=row.dock_count===''?capacity:Number(row.dock_count);if(!publicCode||!name||!city||address===null||latitude===null||longitude===null||!Number.isInteger(capacity)||capacity<0||capacity>200||!Number.isInteger(dockCount)||dockCount<0||dockCount>capacity)errors.push({line,error:'Station invalide'});else normalized.push({line,publicCode,name,city,address,latitude,longitude,capacity,dockCount});}
    else{const publicCode=cleanCode(row.public_code);const stationCode=cleanCode(row.station_code);const position=Number(row.position);if(!publicCode||!stationCode||!Number.isInteger(position)||position<1||position>500)errors.push({line,error:'Dock invalide'});else normalized.push({line,publicCode,stationCode,position});}
  });return{rows:normalized,errors};
}

function duplicateErrors(entity,rows){
  const errors=[];const seen=new Map();const fields=entity==='bikes'?['publicCode','internalCode']:['publicCode'];for(const row of rows)for(const field of fields){const key=`${field}:${String(row[field]).toLowerCase()}`;if(seen.has(key))errors.push({line:row.line,error:`Valeur dupliquée avec la ligne ${seen.get(key)}`});else seen.set(key,row.line);}if(entity==='docks'){const positions=new Map();for(const row of rows){const key=`${row.stationCode.toLowerCase()}:${row.position}`;if(positions.has(key))errors.push({line:row.line,error:`Position dupliquée avec la ligne ${positions.get(key)}`});else positions.set(key,row.line);}}return errors;
}

async function databaseImportErrors(DB,entity,rows){
  const errors=[];if(entity==='stations'){if(rows.reduce((sum,row)=>sum+row.dockCount,0)>300)errors.push({line:1,error:'Maximum 300 docks générés par import'});for(const row of rows){const existing=await DB.prepare('SELECT id FROM stations WHERE lower(public_code)=lower(?) OR lower(slug)=lower(?)').bind(row.publicCode,row.publicCode).first();if(existing)errors.push({line:row.line,error:'Code ou slug déjà utilisé'});}}
  else if(entity==='docks'){const grouped=new Map();for(const row of rows){const station=await DB.prepare("SELECT stations.id,stations.capacity,(SELECT COUNT(*) FROM docks WHERE station_id=stations.id AND status<>'disabled') active_docks FROM stations WHERE lower(public_code)=lower(?)").bind(row.stationCode).first();if(!station){errors.push({line:row.line,error:'Station introuvable'});continue;}const existing=await DB.prepare('SELECT id FROM docks WHERE lower(public_code)=lower(?) OR (station_id=? AND position=?)').bind(row.publicCode,station.id,row.position).first();if(existing)errors.push({line:row.line,error:'Code ou position déjà utilisé'});grouped.set(station.id,{station,count:(grouped.get(station.id)?.count||0)+1,line:row.line});}for(const {station,count,line} of grouped.values())if(Number(station.active_docks)+count>Number(station.capacity))errors.push({line,error:'Capacité de la station dépassée'});}
  else{const demand=new Map();for(const row of rows){const existing=await DB.prepare("SELECT id FROM bikes WHERE lower(public_code)=lower(?) OR lower(code)=lower(?) OR (?<>'' AND lower(COALESCE(serial_number,''))=lower(?))").bind(row.publicCode,row.internalCode,row.serial||'',row.serial||'').first();if(existing)errors.push({line:row.line,error:'Code ou numéro de série déjà utilisé'});if(row.stationCode){const station=await DB.prepare("SELECT stations.id,(SELECT COUNT(*) FROM docks WHERE station_id=stations.id AND status='available' AND bike_id IS NULL) free_docks FROM stations WHERE lower(public_code)=lower(?) AND is_active=1").bind(row.stationCode).first();if(!station)errors.push({line:row.line,error:'Station active introuvable'});else demand.set(station.id,{station,count:(demand.get(station.id)?.count||0)+1,line:row.line});}}for(const {station,count,line} of demand.values())if(count>Number(station.free_docks))errors.push({line,error:'Nombre de docks libres insuffisant'});}return errors;
}

async function validateImportFully(DB,entity,csv){const sourceRows=csvRows(csv);if(!sourceRows.length)return{rows:[],errors:[{line:1,error:'Le CSV ne contient aucune ligne.'}]};const validation=validateImport(entity,sourceRows);validation.errors.push(...duplicateErrors(entity,validation.rows));if(!validation.errors.length)validation.errors.push(...await databaseImportErrors(DB,entity,validation.rows));return validation;}

async function events(DB,json,type,id,url){if(!ASSET_TYPES.has(type)||!id)return fail(json,'TWIN_NOT_FOUND','Jumeau numérique introuvable.',404);const limit=Math.max(10,Math.min(100,Number.parseInt(url.searchParams.get('limit')||'50',10)||50));const result=await DB.prepare(`SELECT infrastructure_events.id,infrastructure_events.event_type,infrastructure_events.from_status,infrastructure_events.to_status,infrastructure_events.from_station_id,infrastructure_events.to_station_id,infrastructure_events.ride_id,infrastructure_events.metadata_json,infrastructure_events.created_at,users.email actor_email FROM infrastructure_events LEFT JOIN users ON users.id=infrastructure_events.actor_user_id WHERE asset_type=? AND asset_id=? ORDER BY infrastructure_events.id DESC LIMIT ?`).bind(type,id,limit).all();return json({events:result.results||[]});}

async function docksList(DB,json,url){
  const search=String(url.searchParams.get('search')||'').trim().slice(0,120);const status=String(url.searchParams.get('status')||'').trim().slice(0,30);const stationId=integer(url.searchParams.get('stationId'))||0;const page=Math.max(1,Number.parseInt(url.searchParams.get('page')||'1',10)||1);const limit=Math.max(10,Math.min(100,Number.parseInt(url.searchParams.get('limit')||'25',10)||25));const offset=(page-1)*limit;const where=`WHERE (?='' OR lower(docks.public_code||' '||stations.name||' '||COALESCE(bikes.public_code,'')) LIKE '%'||lower(?)||'%') AND (?='' OR docks.status=?) AND (?=0 OR docks.station_id=?)`;const bindings=[search,search,status,status,stationId,stationId];
  const[rows,count]=await DB.batch([DB.prepare(`SELECT docks.id,docks.public_code,docks.station_id,docks.position,docks.status,docks.bike_id,docks.lock_status,docks.connectivity_status,docks.last_seen_at,docks.updated_at,stations.name station_name,bikes.public_code bike_code FROM docks JOIN stations ON stations.id=docks.station_id LEFT JOIN bikes ON bikes.id=docks.bike_id ${where} ORDER BY stations.name,docks.position LIMIT ? OFFSET ?`).bind(...bindings,limit,offset),DB.prepare(`SELECT COUNT(*) count FROM docks JOIN stations ON stations.id=docks.station_id LEFT JOIN bikes ON bikes.id=docks.bike_id ${where}`).bind(...bindings)]);const total=Number(count.results?.[0]?.count||0);return json({items:rows.results||[],pagination:{page,limit,total,pages:Math.max(1,Math.ceil(total/limit))}});
}

async function dockDetail(DB,json,id){const dock=await DB.prepare(`SELECT docks.*,stations.name station_name,stations.public_code station_code,bikes.public_code bike_code FROM docks JOIN stations ON stations.id=docks.station_id LEFT JOIN bikes ON bikes.id=docks.bike_id WHERE docks.id=?`).bind(id).first();if(!dock)return fail(json,'DOCK_NOT_FOUND','Dock introuvable.',404);const[inspections,devices,eventRows]=await DB.batch([DB.prepare('SELECT id,public_code,status,outcome,due_at,completed_at FROM inspections WHERE dock_id=? ORDER BY id DESC LIMIT 20').bind(id),DB.prepare('SELECT id,public_code,status,firmware_version,last_seen_at FROM devices WHERE dock_id=? ORDER BY id DESC LIMIT 20').bind(id),DB.prepare("SELECT id,event_type,from_status,to_status,metadata_json,created_at FROM infrastructure_events WHERE asset_type='dock' AND asset_id=? ORDER BY id DESC LIMIT 50").bind(id)]);return json({dock,inspections:inspections.results||[],devices:devices.results||[],events:eventRows.results||[]});}

async function telemetry(request,DB,json,actor,context,type,id,readJson){
  const body=await readJson(request);const connectivity=String(body?.connectivityStatus||'');const lock=String(body?.lockStatus||'unknown');const seen=body?.lastSeenAt?String(body.lastSeenAt):new Date().toISOString();if(!['unknown','online','offline','degraded'].includes(connectivity)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}T/.test(seen))return fail(json,'TWIN_INPUT_INVALID','Télémétrie invalide.');let statement;
  if(type==='station')statement=DB.prepare('UPDATE stations SET connectivity_status=?,last_seen_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(connectivity,seen,id);else{if(!['unknown','locked','unlocked','jammed','offline'].includes(lock))return fail(json,'TWIN_INPUT_INVALID','État de serrure invalide.');const latitude=body?.latitude===undefined?null:finite(body.latitude,-90,90);const longitude=body?.longitude===undefined?null:finite(body.longitude,-180,180);if(type==='bike'&&((body?.latitude!==undefined&&latitude===null)||(body?.longitude!==undefined&&longitude===null)))return fail(json,'TWIN_INPUT_INVALID','Position invalide.');statement=type==='bike'?DB.prepare('UPDATE bikes SET connectivity_status=?,lock_status=?,last_seen_at=?,gps_latitude=COALESCE(?,gps_latitude),gps_longitude=COALESCE(?,gps_longitude),updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(connectivity,lock,seen,latitude,longitude,id):DB.prepare('UPDATE docks SET connectivity_status=?,lock_status=?,last_seen_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(connectivity,lock,seen,id);}
  const result=await statement.run();if(!result.meta.changes)return fail(json,'TWIN_NOT_FOUND','Jumeau numérique introuvable.',404);await DB.batch([DB.prepare("INSERT INTO infrastructure_events(asset_type,asset_id,event_type,actor_user_id,request_id,metadata_json) VALUES (?,?,'telemetry_updated',?,?,?)").bind(type,id,actor.id,context.requestId,JSON.stringify({connectivity,lock})),DB.prepare("INSERT INTO admin_audit_logs(actor_user_id,action,target_type,target_id,request_id,ip_hint,metadata_json) VALUES (?,'twin.telemetry.update',?,?,?,?,?)").bind(actor.id,TABLES[type],String(id),context.requestId,context.ipHint,JSON.stringify({connectivity,lock}))]);return json({success:true});
}

const EXPORTS={
  bikes:{headers:['public_code','code','serial_number','model','status','station_code','dock_code','lock_status','connectivity_status','battery_level','last_seen_at','odometer_meters','total_usage_seconds','total_rides'],sql:`SELECT bikes.public_code,bikes.code,bikes.serial_number,bikes.model,bikes.status,stations.public_code station_code,docks.public_code dock_code,bikes.lock_status,bikes.connectivity_status,bikes.battery_level,bikes.last_seen_at,bikes.odometer_meters,bikes.total_usage_seconds,bikes.total_rides FROM bikes LEFT JOIN stations ON stations.id=bikes.station_id LEFT JOIN docks ON docks.bike_id=bikes.id ORDER BY bikes.id`},
  stations:{headers:['public_code','name','city','address','latitude','longitude','capacity','status','connectivity_status','last_seen_at','bikes','free_docks'],sql:`SELECT stations.public_code,stations.name,stations.city,stations.address,stations.latitude,stations.longitude,stations.capacity,CASE stations.is_active WHEN 1 THEN 'active' ELSE 'inactive' END status,stations.connectivity_status,stations.last_seen_at,(SELECT COUNT(*) FROM bikes WHERE station_id=stations.id) bikes,(SELECT COUNT(*) FROM docks WHERE station_id=stations.id AND status='available') free_docks FROM stations ORDER BY stations.id`},
  docks:{headers:['public_code','station_code','position','status','bike_code','lock_status','connectivity_status','last_seen_at'],sql:`SELECT docks.public_code,stations.public_code station_code,docks.position,docks.status,bikes.public_code bike_code,docks.lock_status,docks.connectivity_status,docks.last_seen_at FROM docks JOIN stations ON stations.id=docks.station_id LEFT JOIN bikes ON bikes.id=docks.bike_id ORDER BY stations.id,docks.position`}
};
const csvCell=(value)=>{const raw=String(value??'');const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replaceAll('"','""')}"`;};
async function bulkExport(DB,json,url){const entity=String(url.searchParams.get('entity')||'');const config=EXPORTS[entity];if(!config)return fail(json,'BULK_ENTITY_INVALID','Type d’export invalide.');const rows=(await DB.prepare(config.sql).all()).results||[];const csv=[config.headers.join(','),...rows.map((row)=>config.headers.map((header)=>csvCell(row[header])).join(','))].join('\r\n');return new Response(csv,{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="pikala-${entity}.csv"`,'cache-control':'no-store'}});}
async function qrBatch(DB,json,url){const ids=idsFrom(url.searchParams.get('ids'));if(!ids.length)return fail(json,'BULK_IDS_REQUIRED','Sélectionnez au moins un vélo.');const placeholders=ids.map(()=>'?').join(',');const rows=(await DB.prepare(`SELECT id,public_code,status FROM bikes WHERE id IN (${placeholders}) ORDER BY public_code`).bind(...ids).all()).results||[];return json({items:rows.map((row)=>({...row,payload:`pikala://bike/${row.public_code}`}))});}

async function previewImport(body,DB,json){try{const validation=await validateImportFully(DB,String(body?.entity||''),body?.csv);return json({entity:body.entity,count:validation.rows.length,preview:validation.rows.slice(0,20),errors:validation.errors,canImport:validation.rows.length>0&&validation.errors.length===0});}catch{return fail(json,'BULK_CSV_INVALID','Le CSV est invalide.');}}

async function commitImport(body,DB,json,actor,context){
  const confirmation=strong(body,'BULK.IMPORT');if(!confirmation)return fail(json,'BULK_CONFIRMATION_REQUIRED','Motif et confirmation forte requis.');const entity=String(body?.entity||'');const duplicate=await DB.prepare('SELECT id FROM admin_overrides WHERE idempotency_key=?').bind(confirmation.idempotencyKey).first();if(duplicate)return json({success:true,idempotent:true});let validation;try{validation=await validateImportFully(DB,entity,body?.csv);}catch{return fail(json,'BULK_CSV_INVALID','Le CSV est invalide.');}if(!validation.rows.length||validation.errors.length)return fail(json,'BULK_IMPORT_INVALID','Corrigez toutes les lignes avant import.',409);
  const statements=[];for(const row of validation.rows){
    if(entity==='stations'){statements.push(DB.prepare("INSERT INTO stations(public_code,slug,name,city,address,latitude,longitude,capacity,bikes_available,is_active,opening_hours_json,connectivity_status,updated_at) VALUES (?,lower(?),?,?,?,?,?,?,0,1,'{}','unknown',CURRENT_TIMESTAMP)").bind(row.publicCode,row.publicCode,row.name,row.city,row.address||null,row.latitude,row.longitude,row.capacity));for(let position=1;position<=row.dockCount;position+=1)statements.push(DB.prepare("INSERT INTO docks(station_id,position,public_code,status) SELECT id,?,?,'available' FROM stations WHERE public_code=?").bind(position,`${row.publicCode}-dock-${String(position).padStart(3,'0')}`,row.publicCode));}
    else if(entity==='docks')statements.push(DB.prepare("INSERT INTO docks(station_id,position,public_code,status) SELECT id,?,?,'available' FROM stations WHERE public_code=?").bind(row.position,row.publicCode,row.stationCode));
    else{statements.push(DB.prepare("INSERT INTO bikes(code,public_code,station_id,status,battery_level,model,serial_number,maintenance_required,updated_at) VALUES (?,?,NULL,'available',?,?,?,0,CURRENT_TIMESTAMP)").bind(row.internalCode,row.publicCode,row.battery,row.model||null,row.serial||null));if(row.stationCode)statements.push(DB.prepare("UPDATE docks SET bike_id=(SELECT id FROM bikes WHERE public_code=?),status='occupied',updated_at=CURRENT_TIMESTAMP WHERE id=(SELECT docks.id FROM docks JOIN stations ON stations.id=docks.station_id WHERE stations.public_code=? AND docks.status='available' AND docks.bike_id IS NULL ORDER BY docks.position LIMIT 1)").bind(row.publicCode,row.stationCode),DB.prepare("UPDATE bikes SET station_id=(SELECT id FROM stations WHERE public_code=?),updated_at=CURRENT_TIMESTAMP WHERE public_code=? AND EXISTS(SELECT 1 FROM docks WHERE bike_id=bikes.id)").bind(row.stationCode,row.publicCode));}
  }
  try{await DB.batch(statements);}catch(error){return fail(json,'BULK_IMPORT_CONFLICT',String(error?.message||'').includes('UNIQUE')?'Un code ou numéro existe déjà.':'L’import viole une contrainte du réseau.',409);}await DB.batch([DB.prepare("INSERT INTO admin_overrides(actor_user_id,action,target_type,target_id,reason,idempotency_key,outcome,request_id,details_json) VALUES (?,'bulk.import',?,'batch',?,?,'applied',?,?)").bind(actor.id,entity,confirmation.reason,confirmation.idempotencyKey,context.requestId,JSON.stringify({count:validation.rows.length})),DB.prepare("INSERT INTO admin_audit_logs(actor_user_id,action,target_type,target_id,request_id,ip_hint,metadata_json) VALUES (?,'bulk.import',?,'batch',?,?,?)").bind(actor.id,entity,context.requestId,context.ipHint,JSON.stringify({count:validation.rows.length,reason:confirmation.reason}))]);return json({success:true,count:validation.rows.length},201);
}

async function auditBulkUpdate(DB,actor,context,confirmation,entity,operation,ids,count,extra={}){await DB.batch([DB.prepare("INSERT INTO admin_overrides(actor_user_id,action,target_type,target_id,reason,idempotency_key,outcome,request_id,details_json) VALUES (?,'bulk.update',?,'batch',?,?,'applied',?,?)").bind(actor.id,entity,confirmation.reason,confirmation.idempotencyKey,context.requestId,JSON.stringify({operation,ids,count,...extra})),DB.prepare("INSERT INTO admin_audit_logs(actor_user_id,action,target_type,target_id,request_id,ip_hint,metadata_json) VALUES (?,'bulk.update',?,'batch',?,?,?)").bind(actor.id,entity,context.requestId,context.ipHint,JSON.stringify({operation,ids,count,reason:confirmation.reason,...extra}))]);}

async function bulkUpdate(body,DB,json,actor,context){
  const confirmation=strong(body,'BULK.UPDATE');if(!confirmation)return fail(json,'BULK_CONFIRMATION_REQUIRED','Motif et confirmation forte requis.');const entity=String(body?.entity||'');const operation=String(body?.operation||'');const ids=idsFrom(body?.ids);if(!ids.length)return fail(json,'BULK_INPUT_INVALID','Sélection invalide.');const duplicate=await DB.prepare('SELECT id FROM admin_overrides WHERE idempotency_key=?').bind(confirmation.idempotencyKey).first();if(duplicate)return json({success:true,idempotent:true});const placeholders=ids.map(()=>'?').join(',');
  if(entity==='bikes'&&operation==='assign_station'){
    const stationId=integer(body?.stationId);if(!stationId)return fail(json,'BULK_INPUT_INVALID','Station invalide.');const station=await DB.prepare("SELECT id,is_active,(SELECT COUNT(*) FROM docks WHERE station_id=stations.id AND status='available' AND bike_id IS NULL) free_docks FROM stations WHERE id=?").bind(stationId).first();const bikes=(await DB.prepare(`SELECT id,status,station_id FROM bikes WHERE id IN (${placeholders})`).bind(...ids).all()).results||[];const idsToMove=bikes.filter((bike)=>Number(bike.station_id)!==stationId).map((bike)=>bike.id);
    if(!station||!station.is_active||bikes.length!==ids.length||bikes.some((bike)=>bike.status==='in_use')||Number(station.free_docks)<idsToMove.length)return fail(json,'BULK_ASSIGNMENT_UNAVAILABLE','Station, vélos ou docks indisponibles.',409);const statements=[];for(const id of idsToMove)statements.push(DB.prepare("UPDATE docks SET bike_id=NULL,status=CASE WHEN status='disabled' THEN status ELSE 'available' END,updated_at=CURRENT_TIMESTAMP WHERE bike_id=?").bind(id),DB.prepare("UPDATE docks SET bike_id=?,status='occupied',updated_at=CURRENT_TIMESTAMP WHERE id=(SELECT id FROM docks WHERE station_id=? AND status='available' AND bike_id IS NULL ORDER BY position LIMIT 1)").bind(id,stationId),DB.prepare('UPDATE bikes SET station_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(stationId,id));try{if(statements.length)await DB.batch(statements);}catch{return fail(json,'BULK_CONSTRAINT','L’assignation viole une contrainte du réseau.',409);}await auditBulkUpdate(DB,actor,context,confirmation,entity,operation,ids,idsToMove.length,{stationId});return json({success:true,count:idsToMove.length});
  }
  let statement;let countStatement;if(entity==='bikes'&&operation==='status'){const status=String(body?.status||'');if(!['available','maintenance','disabled'].includes(status))return fail(json,'BULK_INPUT_INVALID','Statut vélo invalide.');countStatement=DB.prepare(`SELECT COUNT(*) count FROM bikes WHERE id IN (${placeholders}) AND status<>'in_use' AND status<>?`).bind(...ids,status);statement=DB.prepare(`UPDATE bikes SET status=?,maintenance_required=CASE WHEN ?='maintenance' THEN 1 WHEN ?='available' THEN 0 ELSE maintenance_required END,updated_at=CURRENT_TIMESTAMP WHERE id IN (${placeholders}) AND status<>'in_use' AND status<>?`).bind(status,status,status,...ids,status);}else if(entity==='stations'&&operation==='status'){const active=body?.status==='active'?1:body?.status==='inactive'?0:null;if(active===null)return fail(json,'BULK_INPUT_INVALID','Statut station invalide.');countStatement=DB.prepare(`SELECT COUNT(*) count FROM stations WHERE id IN (${placeholders}) AND is_active<>?`).bind(...ids,active);statement=DB.prepare(`UPDATE stations SET is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id IN (${placeholders}) AND is_active<>?`).bind(active,...ids,active);}else if(entity==='docks'&&operation==='status'){const status=String(body?.status||'');if(!['available','maintenance','disabled'].includes(status))return fail(json,'BULK_INPUT_INVALID','Statut dock invalide.');countStatement=DB.prepare(`SELECT COUNT(*) count FROM docks WHERE id IN (${placeholders}) AND bike_id IS NULL AND status<>?`).bind(...ids,status);statement=DB.prepare(`UPDATE docks SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id IN (${placeholders}) AND bike_id IS NULL AND status<>?`).bind(status,...ids,status);}else return fail(json,'BULK_INPUT_INVALID','Opération bulk invalide.');
  const expectedCount=Number((await countStatement.first())?.count||0);try{await statement.run();}catch{return fail(json,'BULK_CONSTRAINT','La modification viole une contrainte du réseau.',409);}await auditBulkUpdate(DB,actor,context,confirmation,entity,operation,ids,expectedCount);return json({success:true,count:expectedCount});
}

export async function handleTwinApi(request,DB,actor,utilities){
  const url=new URL(request.url);const path=url.pathname;const method=request.method;const context={requestId:utilities.requestId,ipHint:utilities.ipHint};let match=path.match(/^\/api\/admin\/twins\/(bike|station|dock)\/([1-9][0-9]*)\/events$/);
  if(match&&method==='GET'){if(!hasPermission(actor,`${match[1]}s.read`))return fail(utilities.json,'FORBIDDEN','Permission insuffisante.',403);return events(DB,utilities.json,match[1],Number(match[2]),url);}match=path.match(/^\/api\/admin\/twins\/(bike|station|dock)\/([1-9][0-9]*)\/telemetry$/);
  if(match&&method==='PATCH'){if(!hasAnyPermission(actor,['devices.manage',`${match[1]}s.manage`]))return fail(utilities.json,'FORBIDDEN','Permission insuffisante.',403);return telemetry(request,DB,utilities.json,actor,context,match[1],Number(match[2]),utilities.readJson);}
  if(path==='/api/admin/docks'&&method==='GET'){if(!hasPermission(actor,'docks.read'))return fail(utilities.json,'FORBIDDEN','Permission insuffisante.',403);return docksList(DB,utilities.json,url);}match=path.match(/^\/api\/admin\/docks\/([1-9][0-9]*)$/);if(match&&method==='GET'){if(!hasPermission(actor,'docks.read'))return fail(utilities.json,'FORBIDDEN','Permission insuffisante.',403);return dockDetail(DB,utilities.json,Number(match[1]));}
  if(path==='/api/admin/bulk/export'&&method==='GET'){const entity=String(url.searchParams.get('entity')||'');if(!BULK_ENTITIES.has(entity))return fail(utilities.json,'BULK_ENTITY_INVALID','Type de ressource invalide.');if(!hasPermission(actor,`${entity}.read`))return fail(utilities.json,'FORBIDDEN','Permission insuffisante.',403);return bulkExport(DB,utilities.json,url);}
  if(path==='/api/admin/bulk/qr'&&method==='GET'){if(!hasPermission(actor,'bikes.read'))return fail(utilities.json,'FORBIDDEN','Permission insuffisante.',403);return qrBatch(DB,utilities.json,url);}
  if((path==='/api/admin/bulk/import/preview'||path==='/api/admin/bulk/import'||path==='/api/admin/bulk/update')&&method==='POST'){const body=await utilities.readJson(request);const entity=String(body?.entity||'');if(!BULK_ENTITIES.has(entity))return fail(utilities.json,'BULK_ENTITY_INVALID','Type de ressource invalide.');if(!hasPermission(actor,`${entity}.manage`))return fail(utilities.json,'FORBIDDEN','Permission insuffisante.',403);if(path.endsWith('/preview'))return previewImport(body,DB,utilities.json);if(path.endsWith('/import'))return commitImport(body,DB,utilities.json,actor,context);return bulkUpdate(body,DB,utilities.json,actor,context);}
  return null;
}
