import { STAFF_ROLE_SET, hasPermission } from '../auth/rbac.js';

const STAFF_STATUSES = new Set(['active','suspended','inactive']);
const integer = (value) => { const parsed=Number(value); return Number.isInteger(parsed)&&parsed>0?parsed:null; };
const text = (value,min,max) => { const result=String(value??'').trim(); return result.length>=min&&result.length<=max?result:null; };
const error = (json,code,message,status=400) => json({code,error:message},status);
const paging = (url) => {const page=Math.max(1,Number.parseInt(url.searchParams.get('page')||'1',10)||1);const limit=Math.max(10,Math.min(100,Number.parseInt(url.searchParams.get('limit')||'25',10)||25));return{page,limit,offset:(page-1)*limit};};
const zonesFrom = (body) => [...new Set((Array.isArray(body?.zoneIds)?body.zoneIds:[]).map(integer).filter(Boolean))].slice(0,50);

function strong(body,action){const reason=text(body?.reason,10,500);const idempotencyKey=text(body?.idempotencyKey,16,120);return reason&&idempotencyKey&&body?.confirmation===`PIKALA ${action}`?{reason,idempotencyKey}:null;}
function canAssign(actor,role){if(!STAFF_ROLE_SET.has(role))return false;if(role==='super_admin'||role==='admin')return hasPermission(actor,'*');return hasPermission(actor,'employees.assign_roles')||hasPermission(actor,'*');}

async function audit(DB,actor,context,staffId,action,reason,metadata={}){const safe=Object.fromEntries(Object.entries(metadata).slice(0,10).map(([key,value])=>[key,typeof value==='string'?value.slice(0,160):value]));await DB.batch([
  DB.prepare(`INSERT INTO staff_activity_logs (staff_member_id,actor_user_id,action,resource_type,resource_id,outcome,request_id,metadata_json) VALUES (?,? ,?,'staff_member',?,'success',?,?)`).bind(staffId,actor.id,action,String(staffId),context.requestId,JSON.stringify({reason,...safe})),
  DB.prepare(`INSERT INTO admin_audit_logs (actor_user_id,action,target_type,target_id,request_id,ip_hint,metadata_json) VALUES (?,?,'staff_member',?,?,?,?)`).bind(actor.id,action,String(staffId),context.requestId,context.ipHint,JSON.stringify({reason,...safe}))
]);context.logEvent?.('admin.action',{requestId:context.requestId,userId:actor.id,resourceType:'staff_member',resourceId:staffId,action,outcome:'success'});}

async function list(DB,json,url){const{page,limit,offset}=paging(url);const search=String(url.searchParams.get('search')||'').trim().slice(0,120);const status=String(url.searchParams.get('status')||'').trim().slice(0,30);const role=String(url.searchParams.get('role')||'').trim().slice(0,40);const where=`WHERE (?='' OR lower(staff_members.employee_code||' '||users.first_name||' '||users.last_name||' '||users.email||' '||COALESCE(users.phone,'')) LIKE '%'||lower(?)||'%') AND (?='' OR staff_members.status=?) AND (?='' OR staff_members.role=?)`;const bindings=[search,search,status,status,role,role];const[rows,count]=await DB.batch([
  DB.prepare(`SELECT staff_members.id,staff_members.user_id,staff_members.employee_code,staff_members.role,staff_members.status,staff_members.hire_date,staff_members.last_activity_at,staff_members.updated_at,users.first_name,users.last_name,users.email,users.phone,COALESCE(group_concat(staff_zones.name,', '),'') zones FROM staff_members JOIN users ON users.id=staff_members.user_id LEFT JOIN staff_member_zones ON staff_member_zones.staff_member_id=staff_members.id LEFT JOIN staff_zones ON staff_zones.id=staff_member_zones.zone_id ${where} GROUP BY staff_members.id ORDER BY staff_members.id DESC LIMIT ? OFFSET ?`).bind(...bindings,limit,offset),
  DB.prepare(`SELECT COUNT(*) count FROM staff_members JOIN users ON users.id=staff_members.user_id ${where}`).bind(...bindings)
]);const total=Number(count.results?.[0]?.count||0);return json({items:rows.results||[],pagination:{page,limit,total,pages:Math.max(1,Math.ceil(total/limit))}});}

async function detail(DB,json,id){const member=await DB.prepare(`SELECT staff_members.*,users.first_name,users.last_name,users.email,users.phone FROM staff_members JOIN users ON users.id=staff_members.user_id WHERE staff_members.id=?`).bind(id).first();if(!member)return error(json,'STAFF_NOT_FOUND','Employé introuvable.',404);const[zones,overrides,activity]=await DB.batch([
  DB.prepare(`SELECT staff_zones.id,staff_zones.code,staff_zones.name,staff_zones.city FROM staff_member_zones JOIN staff_zones ON staff_zones.id=staff_member_zones.zone_id WHERE staff_member_zones.staff_member_id=? ORDER BY staff_zones.name`).bind(id),
  DB.prepare(`SELECT id,permission,effect,reason,expires_at,created_at,revoked_at FROM staff_permission_overrides WHERE staff_member_id=? ORDER BY id DESC LIMIT 100`).bind(id),
  DB.prepare(`SELECT staff_activity_logs.id,staff_activity_logs.action,staff_activity_logs.resource_type,staff_activity_logs.resource_id,staff_activity_logs.outcome,staff_activity_logs.metadata_json,staff_activity_logs.created_at,users.email actor_email FROM staff_activity_logs LEFT JOIN users ON users.id=staff_activity_logs.actor_user_id WHERE staff_activity_logs.staff_member_id=? ORDER BY staff_activity_logs.id DESC LIMIT 100`).bind(id)
]);return json({member,zones:zones.results||[],overrides:overrides.results||[],activity:activity.results||[]});}

async function replaceZones(DB,staffId,ids,actorId){const statements=[DB.prepare('DELETE FROM staff_member_zones WHERE staff_member_id=?').bind(staffId)];for(const zoneId of ids)statements.push(DB.prepare(`INSERT INTO staff_member_zones (staff_member_id,zone_id,assigned_by_user_id) SELECT ?,id,? FROM staff_zones WHERE id=? AND is_active=1`).bind(staffId,actorId,zoneId));await DB.batch(statements);}

async function create(request,DB,json,actor,context,readJson){const body=await readJson(request);const confirmation=strong(body,'STAFF.CREATE');if(!confirmation)return error(json,'STAFF_CONFIRMATION_REQUIRED','Motif et confirmation forte requis.');const email=String(body?.email||'').trim().toLowerCase();const employeeCode=text(body?.employeeCode,3,40);const role=String(body?.role||'');const hireDate=String(body?.hireDate||'');const zoneIds=zonesFrom(body);if(!employeeCode||!canAssign(actor,role)||!/^\d{4}-\d{2}-\d{2}$/.test(hireDate))return error(json,'STAFF_INPUT_INVALID','Employé, rôle ou date invalide.');const duplicate=await DB.prepare('SELECT id FROM admin_overrides WHERE idempotency_key=?').bind(confirmation.idempotencyKey).first();if(duplicate)return json({success:true,idempotent:true});const user=await DB.prepare('SELECT id,email_verified_at,email_verified,status FROM users WHERE lower(email)=?').bind(email).first();if(!user||(!user.email_verified_at&&!user.email_verified)||user.status!=='active')return error(json,'STAFF_USER_INVALID','Le compte doit exister, être actif et avoir un email vérifié.',409);if(await DB.prepare('SELECT id FROM staff_members WHERE user_id=? OR employee_code=?').bind(user.id,employeeCode).first())return error(json,'STAFF_ALREADY_EXISTS','Ce compte ou matricule est déjà employé.',409);const result=await DB.prepare(`INSERT INTO staff_members (user_id,employee_code,role,status,hire_date,created_by_user_id,updated_by_user_id) VALUES (?,?,?,'active',?,?,?)`).bind(user.id,employeeCode,role,hireDate,actor.id,actor.id).run();const id=result.meta.last_row_id;await DB.batch([DB.prepare('UPDATE users SET role=?,auth_version=auth_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(role==='admin'||role==='super_admin'?'admin':'operator',user.id),DB.prepare('UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND revoked_at IS NULL').bind(user.id)]);await replaceZones(DB,id,zoneIds,actor.id);await DB.prepare(`INSERT INTO admin_overrides (actor_user_id,action,target_type,target_id,reason,idempotency_key,outcome,request_id,details_json) VALUES (?,'staff.create','staff_member',?,?,?,'applied',?,?)`).bind(actor.id,String(id),confirmation.reason,confirmation.idempotencyKey,context.requestId,JSON.stringify({role,employeeCode,zoneIds})).run();await audit(DB,actor,context,id,'staff.create',confirmation.reason,{role,employeeCode});return json({success:true,id},201);}

async function update(request,DB,json,actor,context,id,readJson){
  const body=await readJson(request);const confirmation=strong(body,'STAFF.UPDATE');
  if(!confirmation)return error(json,'STAFF_CONFIRMATION_REQUIRED','Motif et confirmation forte requis.');
  const duplicate=await DB.prepare('SELECT id FROM admin_overrides WHERE idempotency_key=?').bind(confirmation.idempotencyKey).first();
  if(duplicate)return json({success:true,idempotent:true});
  const current=await DB.prepare('SELECT staff_members.*,users.id user_id FROM staff_members JOIN users ON users.id=staff_members.user_id WHERE staff_members.id=?').bind(id).first();
  if(!current)return error(json,'STAFF_NOT_FOUND','Employé introuvable.',404);
  const role=String(body?.role||current.role);const status=String(body?.status||current.status);const hireDate=body?.hireDate===undefined?current.hire_date:String(body.hireDate);const zoneIds=body?.zoneIds===undefined?null:zonesFrom(body);
  if(!STAFF_ROLE_SET.has(role)||!STAFF_STATUSES.has(status)||(hireDate&&!/^\d{4}-\d{2}-\d{2}$/.test(hireDate)))return error(json,'STAFF_INPUT_INVALID','Données employé invalides.');
  if(role!==current.role&&!canAssign(actor,role))return error(json,'STAFF_ROLE_FORBIDDEN','Vous ne pouvez pas attribuer ce rôle.',403);
  if(Number(current.user_id)===Number(actor.id)&&(status!=='active'||role!==current.role))return error(json,'STAFF_SELF_LOCKOUT','Vous ne pouvez pas modifier votre propre accès.',409);
  if(current.role==='super_admin'&&(status!=='active'||role!=='super_admin')){const count=await DB.prepare("SELECT COUNT(*) count FROM staff_members WHERE role='super_admin' AND status='active'").first();if(Number(count.count)<=1)return error(json,'STAFF_LAST_SUPER_ADMIN','Le dernier super administrateur doit rester actif.',409);}
  const accessChanged=role!==current.role||status!==current.status;
  const statements=[
    DB.prepare('UPDATE staff_members SET role=?,status=?,hire_date=?,updated_by_user_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(role,status,hireDate||null,actor.id,id),
    DB.prepare("UPDATE users SET role=?,status=CASE WHEN ?='active' THEN 'active' ELSE 'suspended' END,status_reason=?,auth_version=auth_version+?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(role==='admin'||role==='super_admin'?'admin':'operator',status,confirmation.reason,accessChanged?1:0,current.user_id)
  ];
  if(accessChanged)statements.push(DB.prepare('UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND revoked_at IS NULL').bind(current.user_id));
  await DB.batch(statements);if(zoneIds)await replaceZones(DB,id,zoneIds,actor.id);
  await DB.prepare(`INSERT INTO admin_overrides (actor_user_id,action,target_type,target_id,reason,idempotency_key,outcome,request_id,details_json) VALUES (?,'staff.update','staff_member',?,?,?,'applied',?,?)`).bind(actor.id,String(id),confirmation.reason,confirmation.idempotencyKey,context.requestId,JSON.stringify({role,status,zoneIds})).run();
  await audit(DB,actor,context,id,'staff.update',confirmation.reason,{fromRole:current.role,role,fromStatus:current.status,status});return json({success:true});
}

async function permissionOverride(request,DB,json,actor,context,id,readJson){if(!hasPermission(actor,'employees.manage_roles'))return error(json,'STAFF_PERMISSION_FORBIDDEN','Seul un super administrateur peut modifier les permissions individuelles.',403);const body=await readJson(request);const confirmation=strong(body,'STAFF.PERMISSION');if(!confirmation)return error(json,'STAFF_CONFIRMATION_REQUIRED','Motif et confirmation forte requis.');const permission=text(body?.permission,3,80);const effect=String(body?.effect||'');if(!permission||!['grant','deny','revoke'].includes(effect))return error(json,'STAFF_INPUT_INVALID','Permission invalide.');if(effect==='revoke'){const overrideId=integer(body?.overrideId);const result=await DB.prepare('UPDATE staff_permission_overrides SET revoked_at=CURRENT_TIMESTAMP,revoked_by_user_id=? WHERE id=? AND staff_member_id=? AND revoked_at IS NULL').bind(actor.id,overrideId,id).run();if(!result.meta.changes)return error(json,'STAFF_OVERRIDE_NOT_FOUND','Exception active introuvable.',404);}else await DB.prepare(`INSERT INTO staff_permission_overrides (staff_member_id,permission,effect,reason,granted_by_user_id,expires_at) VALUES (?,?,?,?,?,?)`).bind(id,permission,effect,confirmation.reason,actor.id,body?.expiresAt||null).run();await audit(DB,actor,context,id,'staff.permission',confirmation.reason,{permission,effect});return json({success:true},201);}

export async function handleStaffApi(request,DB,actor,utilities){const url=new URL(request.url);const path=url.pathname;const method=request.method;const context={requestId:utilities.requestId,ipHint:utilities.ipHint,logEvent:utilities.logEvent};if(path==='/api/admin/staff'&&method==='GET')return list(DB,utilities.json,url);if(path==='/api/admin/staff'&&method==='POST')return create(request,DB,utilities.json,actor,context,utilities.readJson);let match=path.match(/^\/api\/admin\/staff\/([1-9][0-9]*)$/);if(match&&method==='GET')return detail(DB,utilities.json,Number(match[1]));if(match&&method==='PATCH')return update(request,DB,utilities.json,actor,context,Number(match[1]),utilities.readJson);match=path.match(/^\/api\/admin\/staff\/([1-9][0-9]*)\/permissions$/);if(match&&method==='POST')return permissionOverride(request,DB,utilities.json,actor,context,Number(match[1]),utilities.readJson);return null;}
