import { hasPermission } from '../auth/rbac.js';

const ACTIVE = new Set(['new', 'acknowledged', 'in_progress']);
const STATUSES = new Set([...ACTIVE, 'resolved', 'ignored']);
const TRANSITIONS = Object.freeze({ new:new Set(['acknowledged','in_progress','resolved','ignored']), acknowledged:new Set(['in_progress','resolved','ignored']), in_progress:new Set(['resolved','ignored']), resolved:new Set(['new']), ignored:new Set(['new']) });
const DETAILS = Object.freeze({station_low:['station','Rééquilibrer depuis une station proche.'],station_full:['station','Rééquilibrer vers une station proche.'],long_ride:['ride','Contacter l’utilisateur et vérifier le vélo.'],bike_incidents:['bike','Inspecter le vélo et le maintenir hors location.'],maintenance_due:['maintenance_reminder','Planifier une intervention.'],ticket_urgent:['support_ticket','Assigner le ticket immédiatement.'],bike_dock_inconsistent:['bike','Vérifier physiquement le vélo et le dock.'],field_task_overdue:['field_task','Contacter l’agent ou réassigner la mission.'],device_offline:['device','Contrôler alimentation, réseau et dernière télémétrie.']});

function bounded(value,fallback,min=0,max=100000){const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=min&&parsed<=max?parsed:fallback;}
function safeJson(value,fallback={}){try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:fallback;}catch{return fallback;}}
function clean(value,max){const result=String(value??'').trim();return result&&result.length<=max?result:null;}
function fail(json,code,error,status=400){return json({code,error},status);}
function pagination(url){const page=Math.max(1,Math.min(100000,Number.parseInt(url.searchParams.get('page')||'1',10)||1));const limit=Math.max(10,Math.min(100,Number.parseInt(url.searchParams.get('limit')||'25',10)||25));return{page,limit,offset:(page-1)*limit};}

async function rowsForRule(DB,rule){const t=safeJson(rule.threshold_json);
  if(rule.code==='station_low')return(await DB.prepare(`SELECT s.id,s.name label,COUNT(b.id) value FROM stations s LEFT JOIN bikes b ON b.station_id=s.id AND b.status='available' WHERE s.is_active=1 GROUP BY s.id HAVING COUNT(b.id)<=?`).bind(bounded(t.bikes,2,0,50)).all()).results||[];
  if(rule.code==='station_full')return(await DB.prepare(`SELECT s.id,s.name label,MAX(0,s.capacity-COUNT(d.id)) value FROM stations s LEFT JOIN docks d ON d.station_id=s.id AND d.status='occupied' WHERE s.is_active=1 GROUP BY s.id HAVING MAX(0,s.capacity-COUNT(d.id))<=?`).bind(bounded(t.freeDocks,2,0,50)).all()).results||[];
  if(rule.code==='long_ride')return(await DB.prepare(`SELECT id,'Trajet #'||id label,CAST((julianday('now')-julianday(started_at))*1440 AS INTEGER) value FROM rides WHERE status='active' AND started_at<datetime('now','-'||?||' minutes')`).bind(bounded(t.minutes,180,30,1440)).all()).results||[];
  if(rule.code==='bike_incidents')return(await DB.prepare(`SELECT b.id,b.public_code label,COUNT(i.id) value FROM bikes b JOIN bike_incidents i ON i.bike_id=b.id AND i.status IN ('open','triaged','in_progress') GROUP BY b.id HAVING COUNT(i.id)>=?`).bind(bounded(t.count,3,1,100)).all()).results||[];
  if(rule.code==='maintenance_due')return(await DB.prepare(`SELECT id,reason label,CAST((julianday('now')-julianday(COALESCE(due_at,detected_at)))*24 AS INTEGER) value FROM maintenance_reminders WHERE status='open' AND COALESCE(due_at,detected_at)<CURRENT_TIMESTAMP`).all()).results||[];
  if(rule.code==='ticket_urgent')return(await DB.prepare(`SELECT id,subject label,CAST((julianday('now')-julianday(updated_at))*1440 AS INTEGER) value FROM support_tickets WHERE priority='urgent' AND status IN ('open','in_progress') AND updated_at<datetime('now','-'||?||' minutes')`).bind(bounded(t.minutes,60,5,10080)).all()).results||[];
  if(rule.code==='field_task_overdue')return(await DB.prepare(`SELECT id,public_code label,CAST((julianday('now')-julianday(due_at))*1440 AS INTEGER) value FROM field_tasks WHERE status NOT IN ('completed','cancelled') AND due_at IS NOT NULL AND due_at<CURRENT_TIMESTAMP`).all()).results||[];
  if(rule.code==='device_offline')return(await DB.prepare(`SELECT id,public_code label,CAST((julianday('now')-julianday(COALESCE(last_seen_at,created_at)))*1440 AS INTEGER) value FROM devices WHERE status NOT IN ('disabled','maintenance') AND (status='offline' OR COALESCE(last_seen_at,created_at)<datetime('now','-'||?||' minutes'))`).bind(bounded(t.minutes,30,5,10080)).all()).results||[];
  if(rule.code==='bike_dock_inconsistent')return(await DB.prepare(`SELECT b.id,b.public_code label,1 value FROM bikes b LEFT JOIN docks d ON d.bike_id=b.id WHERE (b.status='in_use' AND d.id IS NOT NULL) OR (b.status='available' AND (b.station_id IS NULL OR d.id IS NULL OR d.station_id<>b.station_id)) OR (d.id IS NOT NULL AND d.status<>'occupied') UNION SELECT COALESCE(d.bike_id,d.id),'Dock '||d.public_code,1 FROM docks d LEFT JOIN bikes b ON b.id=d.bike_id WHERE d.status='occupied' AND (d.bike_id IS NULL OR b.id IS NULL)`).all()).results||[];
  return[];
}

async function createOrRefresh(DB,rule,row){const[resourceType,recommendation]=DETAILS[rule.code]||['resource',null];const key=`${rule.code}:${resourceType}:${row.id}`;const existing=await DB.prepare(`SELECT id,status,last_detected_at FROM supervision_alerts WHERE dedupe_key=? ORDER BY id DESC LIMIT 1`).bind(key).first();if(existing&&ACTIVE.has(existing.status)){await DB.prepare('UPDATE supervision_alerts SET last_detected_at=CURRENT_TIMESTAMP,metadata_json=? WHERE id=?').bind(JSON.stringify({value:row.value??null}),existing.id).run();return{created:false,automatic:false};}if(existing){const cooling=await DB.prepare(`SELECT 1 ok FROM supervision_alerts WHERE id=? AND last_detected_at>datetime('now','-'||?||' seconds')`).bind(existing.id,rule.cooldown_seconds).first();if(cooling)return{created:false,automatic:false};}const inserted=await DB.prepare(`INSERT INTO supervision_alerts(rule_id,dedupe_key,severity,resource_type,resource_id,title,message,recommendation,metadata_json) VALUES(?,?,?,?,?,?,?,?,?)`).bind(rule.id,key,rule.severity,resourceType,String(row.id),rule.name,`${rule.description} ${row.label||row.id}`,recommendation,JSON.stringify({value:row.value??null})).run();const alertId=inserted.meta.last_row_id;await DB.prepare(`INSERT INTO supervision_alert_events(alert_id,event_type,details_json) VALUES(?,'detected',?)`).bind(alertId,JSON.stringify({rule:rule.code,resourceType,resourceId:row.id})).run();let automatic=false;if(rule.automatic_action==='bike_maintenance'&&resourceType==='bike'){const changed=await DB.prepare(`UPDATE bikes SET status='maintenance',maintenance_required=1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='available'`).bind(row.id).run();automatic=Boolean(changed.meta.changes);if(automatic)await DB.prepare(`INSERT INTO supervision_alert_events(alert_id,event_type,details_json) VALUES(?,'automatic_action',?)`).bind(alertId,JSON.stringify({action:'bike_maintenance',reversible:true})).run();}return{created:true,automatic};}

export async function runSupervision(DB){const rules=(await DB.prepare('SELECT * FROM supervision_rules WHERE is_active=1 ORDER BY id').all()).results||[];let evaluated=0,created=0,automatic=0;for(const rule of rules){const rows=await rowsForRule(DB,rule);evaluated+=rows.length;for(const row of rows){const result=await createOrRefresh(DB,rule,row);if(result.created)created++;if(result.automatic)automatic++;}}return{rules:rules.length,evaluated,created,automatic};}

async function listAlerts(DB,json,url){const{page,limit,offset}=pagination(url);const status=String(url.searchParams.get('status')||''),severity=String(url.searchParams.get('severity')||''),category=String(url.searchParams.get('category')||''),search=String(url.searchParams.get('search')||'').trim().slice(0,120);if(status&&!STATUSES.has(status))return fail(json,'SUPERVISION_FILTER_INVALID','Filtre de statut invalide.');const where=`WHERE (?='' OR a.status=?) AND (?='' OR a.severity=?) AND (?='' OR r.category=?) AND (?='' OR lower(a.title||' '||a.message||' '||a.resource_type||' '||a.resource_id) LIKE '%'||lower(?)||'%')`;const bindings=[status,status,severity,severity,category,category,search,search];const[rows,count]=await DB.batch([DB.prepare(`SELECT a.*,r.code rule_code,r.category,r.automatic_action FROM supervision_alerts a JOIN supervision_rules r ON r.id=a.rule_id ${where} ORDER BY CASE a.severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,a.last_detected_at DESC LIMIT ? OFFSET ?`).bind(...bindings,limit,offset),DB.prepare(`SELECT COUNT(*) count FROM supervision_alerts a JOIN supervision_rules r ON r.id=a.rule_id ${where}`).bind(...bindings)]);const total=Number(count.results?.[0]?.count||0);return json({items:rows.results||[],pagination:{page,limit,total,pages:Math.max(1,Math.ceil(total/limit))}});}
async function listRules(DB,json){const items=(await DB.prepare(`SELECT id,code public_code,name,category rule_type,description,threshold_json,severity,is_active,automatic_action,notify,cooldown_seconds,updated_at FROM supervision_rules ORDER BY category,name`).all()).results||[];return json({items:items.map(item=>({...item,status:item.is_active?'active':'disabled'})),pagination:{page:1,limit:items.length,total:items.length,pages:1}});}
async function history(DB,json,id){const alert=await DB.prepare(`SELECT a.*,r.code rule_code,r.category FROM supervision_alerts a JOIN supervision_rules r ON r.id=a.rule_id WHERE a.id=?`).bind(id).first();if(!alert)return fail(json,'SUPERVISION_NOT_FOUND','Alerte introuvable.',404);const events=(await DB.prepare(`SELECT e.id,e.event_type,e.details_json,e.created_at,u.email actor_email FROM supervision_alert_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.alert_id=? ORDER BY e.id`).bind(id).all()).results||[];return json({alert,events});}
async function changeStatus(request,DB,json,actor,context,id,readJson){const body=await readJson(request);const target=String(body?.status||''),reason=clean(body?.reason,500);if(!STATUSES.has(target)||!reason||reason.length<10)return fail(json,'SUPERVISION_INPUT_INVALID','Statut et motif de 10 caractères minimum requis.');const current=await DB.prepare('SELECT id,status FROM supervision_alerts WHERE id=?').bind(id).first();if(!current)return fail(json,'SUPERVISION_NOT_FOUND','Alerte introuvable.',404);if(!TRANSITIONS[current.status]?.has(target))return fail(json,'SUPERVISION_TRANSITION_INVALID','Transition d’alerte invalide.',409);const result=await DB.prepare(`UPDATE supervision_alerts SET status=?,acknowledged_by_user_id=CASE WHEN ?='acknowledged' THEN ? ELSE acknowledged_by_user_id END,acknowledged_at=CASE WHEN ?='acknowledged' THEN CURRENT_TIMESTAMP ELSE acknowledged_at END,in_progress_by_user_id=CASE WHEN ?='in_progress' THEN ? ELSE in_progress_by_user_id END,in_progress_at=CASE WHEN ?='in_progress' THEN CURRENT_TIMESTAMP ELSE in_progress_at END,resolved_by_user_id=CASE WHEN ?='resolved' THEN ? ELSE resolved_by_user_id END,resolved_at=CASE WHEN ?='resolved' THEN CURRENT_TIMESTAMP ELSE resolved_at END,ignored_by_user_id=CASE WHEN ?='ignored' THEN ? ELSE ignored_by_user_id END,ignored_at=CASE WHEN ?='ignored' THEN CURRENT_TIMESTAMP ELSE ignored_at END WHERE id=? AND status=?`).bind(target,target,actor.id,target,target,actor.id,target,target,actor.id,target,target,actor.id,target,id,current.status).run();if(!result.meta.changes)return fail(json,'SUPERVISION_CONFLICT','Alerte modifiée par une autre requête.',409);await DB.batch([DB.prepare(`INSERT INTO supervision_alert_events(alert_id,actor_user_id,event_type,details_json) VALUES(?,?,?,?)`).bind(id,actor.id,'status_changed',JSON.stringify({from:current.status,to:target,reason})),DB.prepare(`INSERT INTO admin_audit_logs(actor_user_id,action,target_type,target_id,request_id,ip_hint,metadata_json) VALUES(?,'supervision.alert.status','supervision_alert',?,?,?,?)`).bind(actor.id,String(id),context.requestId,context.ipHint,JSON.stringify({from:current.status,to:target,reason}))]);return json({success:true,status:target});}
async function updateRule(request,DB,json,actor,context,id,readJson){const body=await readJson(request),active=body?.isActive===true||body?.isActive===1,notify=body?.notify===true||body?.notify===1,cooldown=bounded(body?.cooldownSeconds,NaN,60,604800),threshold=body?.threshold&&typeof body.threshold==='object'&&!Array.isArray(body.threshold)?body.threshold:null;if(!Number.isFinite(cooldown)||!threshold||JSON.stringify(threshold).length>1000)return fail(json,'SUPERVISION_INPUT_INVALID','Configuration de règle invalide.');const result=await DB.prepare(`UPDATE supervision_rules SET is_active=?,notify=?,cooldown_seconds=?,threshold_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(active?1:0,notify?1:0,cooldown,JSON.stringify(threshold),id).run();if(!result.meta.changes)return fail(json,'SUPERVISION_NOT_FOUND','Règle introuvable.',404);await DB.prepare(`INSERT INTO admin_audit_logs(actor_user_id,action,target_type,target_id,request_id,ip_hint,metadata_json) VALUES(?,'supervision.rule.update','supervision_rule',?,?,?,?)`).bind(actor.id,String(id),context.requestId,context.ipHint,JSON.stringify({active,notify,cooldown})).run();return json({success:true});}

export async function handleSupervisionApi(request,DB,actor,utilities){const url=new URL(request.url),path=url.pathname,{json,readJson,requestId,ipHint}=utilities,context={requestId,ipHint};if(request.method==='GET'&&['/api/admin/supervision/alerts','/api/admin/control-center/alerts'].includes(path))return listAlerts(DB,json,url);if(request.method==='GET'&&['/api/admin/supervision/rules','/api/admin/control-center/automations'].includes(path))return listRules(DB,json);let match=path.match(/^\/api\/admin\/supervision\/alerts\/([1-9][0-9]*)\/history$/);if(match&&request.method==='GET')return history(DB,json,Number(match[1]));match=path.match(/^\/api\/admin\/supervision\/alerts\/([1-9][0-9]*)\/status$/);if(match&&request.method==='POST'){if(!hasPermission(actor,'alerts.manage'))return fail(json,'FORBIDDEN','Permission insuffisante.',403);return changeStatus(request,DB,json,actor,context,Number(match[1]),readJson);}match=path.match(/^\/api\/admin\/supervision\/rules\/([1-9][0-9]*)$/);if(match&&request.method==='PATCH'){if(!hasPermission(actor,'automations.manage'))return fail(json,'FORBIDDEN','Permission insuffisante.',403);return updateRule(request,DB,json,actor,context,Number(match[1]),readJson);}if(path==='/api/admin/supervision/run'&&request.method==='POST'){if(!hasPermission(actor,'automations.manage'))return fail(json,'FORBIDDEN','Permission insuffisante.',403);const result=await runSupervision(DB);await DB.prepare(`INSERT INTO admin_audit_logs(actor_user_id,action,target_type,target_id,request_id,ip_hint,metadata_json) VALUES(?,'supervision.run','supervision','manual',?,?,?)`).bind(actor.id,context.requestId,context.ipHint,JSON.stringify(result)).run();return json(result,201);}return null;}
